replicas: 2

args:
  - --kubelet-preferred-address-types=InternalIP,Hostname

podDisruptionBudget:
  enabled: true
  minAvailable: 1

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 250m
    memory: 256Mi
