/**
 * Authentication and authorization error codes.
 *
 * Keep public auth errors broad enough to avoid leaking sensitive details.
 * For example, return `INVALID_CREDENTIALS` instead of revealing whether an
 * email, username, or password was incorrect.
 */
export declare const AuthErrorCode: {
  readonly INVALID_CREDENTIALS: 'INVALID_CREDENTIALS';
  readonly INVALID_EMAIL: 'INVALID_EMAIL';
  readonly INVALID_PASSWORD: 'INVALID_PASSWORD';
  readonly EMAIL_REQUIRED: 'EMAIL_REQUIRED';
  readonly PASSWORD_REQUIRED: 'PASSWORD_REQUIRED';
  readonly PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT';
  readonly PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG';
  readonly PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK';
  readonly PASSWORD_REUSED: 'PASSWORD_REUSED';
  readonly USERNAME_REQUIRED: 'USERNAME_REQUIRED';
  readonly USERNAME_INVALID: 'USERNAME_INVALID';
  readonly USERNAME_TOO_SHORT: 'USERNAME_TOO_SHORT';
  readonly USERNAME_TOO_LONG: 'USERNAME_TOO_LONG';
  readonly USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN';
  readonly EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED';
  readonly EMAIL_NOT_REGISTERED: 'EMAIL_NOT_REGISTERED';
  readonly EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED';
  readonly EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED';
  readonly EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED';
  readonly EMAIL_VERIFICATION_EXPIRED: 'EMAIL_VERIFICATION_EXPIRED';
  readonly EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED';
  readonly ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND';
  readonly ACCOUNT_DISABLED: 'ACCOUNT_DISABLED';
  readonly ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED';
  readonly ACCOUNT_DELETED: 'ACCOUNT_DELETED';
  readonly ACCOUNT_LOCKED: 'ACCOUNT_LOCKED';
  readonly ACCOUNT_PENDING_VERIFICATION: 'ACCOUNT_PENDING_VERIFICATION';
  readonly INVALID_SESSION: 'INVALID_SESSION';
  readonly SESSION_NOT_FOUND: 'SESSION_NOT_FOUND';
  readonly SESSION_EXPIRED: 'SESSION_EXPIRED';
  readonly SESSION_REVOKED: 'SESSION_REVOKED';
  readonly SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED';
  readonly SESSION_REFRESH_FAILED: 'SESSION_REFRESH_FAILED';
  readonly INVALID_TOKEN: 'INVALID_TOKEN';
  readonly INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN';
  readonly INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN';
  readonly INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN';
  readonly INVALID_PASSWORD_RESET_TOKEN: 'INVALID_PASSWORD_RESET_TOKEN';
  readonly TOKEN_MISSING: 'TOKEN_MISSING';
  readonly TOKEN_EXPIRED: 'TOKEN_EXPIRED';
  readonly TOKEN_REVOKED: 'TOKEN_REVOKED';
  readonly TOKEN_SIGNATURE_INVALID: 'TOKEN_SIGNATURE_INVALID';
  readonly TOKEN_AUDIENCE_INVALID: 'TOKEN_AUDIENCE_INVALID';
  readonly TOKEN_ISSUER_INVALID: 'TOKEN_ISSUER_INVALID';
  readonly TOKEN_TYPE_INVALID: 'TOKEN_TYPE_INVALID';
  readonly TOKEN_PAYLOAD_INVALID: 'TOKEN_PAYLOAD_INVALID';
  readonly MFA_REQUIRED: 'MFA_REQUIRED';
  readonly MFA_NOT_ENABLED: 'MFA_NOT_ENABLED';
  readonly MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED';
  readonly MFA_CODE_INVALID: 'MFA_CODE_INVALID';
  readonly MFA_CODE_EXPIRED: 'MFA_CODE_EXPIRED';
  readonly MFA_CHALLENGE_FAILED: 'MFA_CHALLENGE_FAILED';
  readonly MFA_RECOVERY_CODE_INVALID: 'MFA_RECOVERY_CODE_INVALID';
  readonly MFA_RECOVERY_CODE_USED: 'MFA_RECOVERY_CODE_USED';
  readonly PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED';
  readonly PASSWORD_RESET_EXPIRED: 'PASSWORD_RESET_EXPIRED';
  readonly PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED';
  readonly PASSWORD_RESET_REQUEST_FAILED: 'PASSWORD_RESET_REQUEST_FAILED';
  readonly PERMISSION_DENIED: 'PERMISSION_DENIED';
  readonly ROLE_REQUIRED: 'ROLE_REQUIRED';
  readonly INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS';
  readonly PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND';
  readonly PROVIDER_DISABLED: 'PROVIDER_DISABLED';
  readonly PROVIDER_ACCOUNT_NOT_LINKED: 'PROVIDER_ACCOUNT_NOT_LINKED';
  readonly PROVIDER_ACCOUNT_ALREADY_LINKED: 'PROVIDER_ACCOUNT_ALREADY_LINKED';
  readonly PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED';
  readonly AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED';
  readonly AUTH_SERVICE_UNAVAILABLE: 'AUTH_SERVICE_UNAVAILABLE';
  readonly AUTH_CONFIGURATION_INVALID: 'AUTH_CONFIGURATION_INVALID';
  readonly JWKS_UNAVAILABLE: 'JWKS_UNAVAILABLE';
  readonly SIGNING_KEY_UNAVAILABLE: 'SIGNING_KEY_UNAVAILABLE';
  readonly AUTH_UNKNOWN_ERROR: 'AUTH_UNKNOWN_ERROR';
};
export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];
export declare const AuthErrorCodeValues: (
  | 'INVALID_CREDENTIALS'
  | 'INVALID_EMAIL'
  | 'INVALID_PASSWORD'
  | 'EMAIL_REQUIRED'
  | 'PASSWORD_REQUIRED'
  | 'PASSWORD_TOO_SHORT'
  | 'PASSWORD_TOO_LONG'
  | 'PASSWORD_TOO_WEAK'
  | 'PASSWORD_REUSED'
  | 'USERNAME_REQUIRED'
  | 'USERNAME_INVALID'
  | 'USERNAME_TOO_SHORT'
  | 'USERNAME_TOO_LONG'
  | 'USERNAME_ALREADY_TAKEN'
  | 'EMAIL_ALREADY_REGISTERED'
  | 'EMAIL_NOT_REGISTERED'
  | 'EMAIL_NOT_VERIFIED'
  | 'EMAIL_ALREADY_VERIFIED'
  | 'EMAIL_VERIFICATION_REQUIRED'
  | 'EMAIL_VERIFICATION_EXPIRED'
  | 'EMAIL_VERIFICATION_FAILED'
  | 'ACCOUNT_NOT_FOUND'
  | 'ACCOUNT_DISABLED'
  | 'ACCOUNT_SUSPENDED'
  | 'ACCOUNT_DELETED'
  | 'ACCOUNT_LOCKED'
  | 'ACCOUNT_PENDING_VERIFICATION'
  | 'INVALID_SESSION'
  | 'SESSION_NOT_FOUND'
  | 'SESSION_EXPIRED'
  | 'SESSION_REVOKED'
  | 'SESSION_CREATION_FAILED'
  | 'SESSION_REFRESH_FAILED'
  | 'INVALID_TOKEN'
  | 'INVALID_ACCESS_TOKEN'
  | 'INVALID_REFRESH_TOKEN'
  | 'INVALID_VERIFICATION_TOKEN'
  | 'INVALID_PASSWORD_RESET_TOKEN'
  | 'TOKEN_MISSING'
  | 'TOKEN_EXPIRED'
  | 'TOKEN_REVOKED'
  | 'TOKEN_SIGNATURE_INVALID'
  | 'TOKEN_AUDIENCE_INVALID'
  | 'TOKEN_ISSUER_INVALID'
  | 'TOKEN_TYPE_INVALID'
  | 'TOKEN_PAYLOAD_INVALID'
  | 'MFA_REQUIRED'
  | 'MFA_NOT_ENABLED'
  | 'MFA_ALREADY_ENABLED'
  | 'MFA_CODE_INVALID'
  | 'MFA_CODE_EXPIRED'
  | 'MFA_CHALLENGE_FAILED'
  | 'MFA_RECOVERY_CODE_INVALID'
  | 'MFA_RECOVERY_CODE_USED'
  | 'PASSWORD_RESET_REQUIRED'
  | 'PASSWORD_RESET_EXPIRED'
  | 'PASSWORD_RESET_FAILED'
  | 'PASSWORD_RESET_REQUEST_FAILED'
  | 'PERMISSION_DENIED'
  | 'ROLE_REQUIRED'
  | 'INSUFFICIENT_PERMISSIONS'
  | 'PROVIDER_NOT_FOUND'
  | 'PROVIDER_DISABLED'
  | 'PROVIDER_ACCOUNT_NOT_LINKED'
  | 'PROVIDER_ACCOUNT_ALREADY_LINKED'
  | 'PROVIDER_AUTH_FAILED'
  | 'AUTH_RATE_LIMITED'
  | 'AUTH_SERVICE_UNAVAILABLE'
  | 'AUTH_CONFIGURATION_INVALID'
  | 'JWKS_UNAVAILABLE'
  | 'SIGNING_KEY_UNAVAILABLE'
  | 'AUTH_UNKNOWN_ERROR'
)[];
export declare function isAuthErrorCode(value: unknown): value is AuthErrorCode;
