/**
 * Authentication and authorization error codes.
 *
 * Keep public auth errors broad enough to avoid leaking sensitive details.
 * For example, return `INVALID_CREDENTIALS` instead of revealing whether an
 * email, username, or password was incorrect.
 */
export const AuthErrorCode = {
  // Credentials and input.
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD', //NOSONAR Error-code identifier, not a credential.

  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED', //NOSONAR Error-code identifier, not a credential.
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT', //NOSONAR Error-code identifier, not a credential.
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG', //NOSONAR Error-code identifier, not a credential.
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK', //NOSONAR Error-code identifier, not a credential.
  PASSWORD_REUSED: 'PASSWORD_REUSED', //NOSONAR Error-code identifier, not a credential.

  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  USERNAME_INVALID: 'USERNAME_INVALID',
  USERNAME_TOO_SHORT: 'USERNAME_TOO_SHORT',
  USERNAME_TOO_LONG: 'USERNAME_TOO_LONG',
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',

  // Email verification.
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_REGISTERED: 'EMAIL_NOT_REGISTERED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  EMAIL_VERIFICATION_EXPIRED: 'EMAIL_VERIFICATION_EXPIRED',
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',

  // Account state.
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_PENDING_VERIFICATION: 'ACCOUNT_PENDING_VERIFICATION',

  // Sessions.
  INVALID_SESSION: 'INVALID_SESSION',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
  SESSION_REFRESH_FAILED: 'SESSION_REFRESH_FAILED',

  // Tokens.
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  INVALID_PASSWORD_RESET_TOKEN: 'INVALID_PASSWORD_RESET_TOKEN', //NOSONAR Error-code identifier, not a credential.

  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  TOKEN_SIGNATURE_INVALID: 'TOKEN_SIGNATURE_INVALID',
  TOKEN_AUDIENCE_INVALID: 'TOKEN_AUDIENCE_INVALID',
  TOKEN_ISSUER_INVALID: 'TOKEN_ISSUER_INVALID',
  TOKEN_TYPE_INVALID: 'TOKEN_TYPE_INVALID',
  TOKEN_PAYLOAD_INVALID: 'TOKEN_PAYLOAD_INVALID',

  // Multi-factor authentication.
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_NOT_ENABLED: 'MFA_NOT_ENABLED',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  MFA_CODE_INVALID: 'MFA_CODE_INVALID',
  MFA_CODE_EXPIRED: 'MFA_CODE_EXPIRED',
  MFA_CHALLENGE_FAILED: 'MFA_CHALLENGE_FAILED',
  MFA_RECOVERY_CODE_INVALID: 'MFA_RECOVERY_CODE_INVALID',
  MFA_RECOVERY_CODE_USED: 'MFA_RECOVERY_CODE_USED',

  // Password reset.
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED', //NOSONAR Error-code identifier, not a credential.
  PASSWORD_RESET_EXPIRED: 'PASSWORD_RESET_EXPIRED', //NOSONAR Error-code identifier, not a credential.
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED', //NOSONAR Error-code identifier, not a credential.
  PASSWORD_RESET_REQUEST_FAILED: 'PASSWORD_RESET_REQUEST_FAILED', //NOSONAR Error-code identifier, not a credential.

  // Authorization.
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ROLE_REQUIRED: 'ROLE_REQUIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // External identity providers.
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_DISABLED: 'PROVIDER_DISABLED',
  PROVIDER_ACCOUNT_NOT_LINKED: 'PROVIDER_ACCOUNT_NOT_LINKED',
  PROVIDER_ACCOUNT_ALREADY_LINKED: 'PROVIDER_ACCOUNT_ALREADY_LINKED',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',

  // Service and configuration failures.
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_SERVICE_UNAVAILABLE: 'AUTH_SERVICE_UNAVAILABLE',
  AUTH_CONFIGURATION_INVALID: 'AUTH_CONFIGURATION_INVALID',
  JWKS_UNAVAILABLE: 'JWKS_UNAVAILABLE',
  SIGNING_KEY_UNAVAILABLE: 'SIGNING_KEY_UNAVAILABLE',

  // Fallback.
  AUTH_UNKNOWN_ERROR: 'AUTH_UNKNOWN_ERROR',
} as const

export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode]

export const AuthErrorCodeValues = Object.values(AuthErrorCode)

export function isAuthErrorCode(value: unknown): value is AuthErrorCode {
  return (
    typeof value === 'string' &&
    AuthErrorCodeValues.includes(value as AuthErrorCode)
  )
}
