/**
 * Database infrastructure and persistence error codes.
 *
 * Use domain-specific errors for business failures.
 * For example, use `UserErrorCode.USER_NOT_FOUND` instead of a database
 * record-not-found error when looking up a user.
 */
export declare const DatabaseErrorCode: {
  readonly DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED';
  readonly DATABASE_CONNECTION_TIMEOUT: 'DATABASE_CONNECTION_TIMEOUT';
  readonly DATABASE_POOL_EXHAUSTED: 'DATABASE_POOL_EXHAUSTED';
  readonly DATABASE_TIMEOUT: 'DATABASE_TIMEOUT';
  readonly DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE';
  readonly DATABASE_QUERY_FAILED: 'DATABASE_QUERY_FAILED';
  readonly DATABASE_QUERY_TIMEOUT: 'DATABASE_QUERY_TIMEOUT';
  readonly DATABASE_INVALID_QUERY: 'DATABASE_INVALID_QUERY';
  readonly DATABASE_READ_FAILED: 'DATABASE_READ_FAILED';
  readonly DATABASE_WRITE_FAILED: 'DATABASE_WRITE_FAILED';
  readonly DATABASE_TRANSACTION_FAILED: 'DATABASE_TRANSACTION_FAILED';
  readonly DATABASE_TRANSACTION_COMMIT_FAILED: 'DATABASE_TRANSACTION_COMMIT_FAILED';
  readonly DATABASE_TRANSACTION_ROLLBACK_FAILED: 'DATABASE_TRANSACTION_ROLLBACK_FAILED';
  readonly DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION';
  readonly DATABASE_UNIQUE_CONSTRAINT_VIOLATION: 'DATABASE_UNIQUE_CONSTRAINT_VIOLATION';
  readonly DATABASE_FOREIGN_KEY_VIOLATION: 'DATABASE_FOREIGN_KEY_VIOLATION';
  readonly DATABASE_NOT_NULL_CONSTRAINT_VIOLATION: 'DATABASE_NOT_NULL_CONSTRAINT_VIOLATION';
  readonly DATABASE_CHECK_CONSTRAINT_VIOLATION: 'DATABASE_CHECK_CONSTRAINT_VIOLATION';
  readonly DATABASE_DEADLOCK_DETECTED: 'DATABASE_DEADLOCK_DETECTED';
  readonly DATABASE_LOCK_TIMEOUT: 'DATABASE_LOCK_TIMEOUT';
  readonly DATABASE_SERIALIZATION_FAILURE: 'DATABASE_SERIALIZATION_FAILURE';
  readonly DATABASE_MIGRATION_FAILED: 'DATABASE_MIGRATION_FAILED';
  readonly DATABASE_MIGRATION_ROLLBACK_FAILED: 'DATABASE_MIGRATION_ROLLBACK_FAILED';
  readonly DATABASE_SCHEMA_SYNC_FAILED: 'DATABASE_SCHEMA_SYNC_FAILED';
  readonly DATABASE_SCHEMA_NOT_FOUND: 'DATABASE_SCHEMA_NOT_FOUND';
  readonly DATABASE_TABLE_NOT_FOUND: 'DATABASE_TABLE_NOT_FOUND';
  readonly DATABASE_COLUMN_NOT_FOUND: 'DATABASE_COLUMN_NOT_FOUND';
  readonly DATABASE_CONFIGURATION_INVALID: 'DATABASE_CONFIGURATION_INVALID';
  readonly DATABASE_DRIVER_ERROR: 'DATABASE_DRIVER_ERROR';
  readonly DATABASE_HEALTH_CHECK_FAILED: 'DATABASE_HEALTH_CHECK_FAILED';
  readonly DATABASE_UNKNOWN_ERROR: 'DATABASE_UNKNOWN_ERROR';
};
export type DatabaseErrorCode =
  (typeof DatabaseErrorCode)[keyof typeof DatabaseErrorCode];
export declare const DatabaseErrorCodeValues: (
  | 'DATABASE_CONNECTION_FAILED'
  | 'DATABASE_CONNECTION_TIMEOUT'
  | 'DATABASE_POOL_EXHAUSTED'
  | 'DATABASE_TIMEOUT'
  | 'DATABASE_UNAVAILABLE'
  | 'DATABASE_QUERY_FAILED'
  | 'DATABASE_QUERY_TIMEOUT'
  | 'DATABASE_INVALID_QUERY'
  | 'DATABASE_READ_FAILED'
  | 'DATABASE_WRITE_FAILED'
  | 'DATABASE_TRANSACTION_FAILED'
  | 'DATABASE_TRANSACTION_COMMIT_FAILED'
  | 'DATABASE_TRANSACTION_ROLLBACK_FAILED'
  | 'DATABASE_CONSTRAINT_VIOLATION'
  | 'DATABASE_UNIQUE_CONSTRAINT_VIOLATION'
  | 'DATABASE_FOREIGN_KEY_VIOLATION'
  | 'DATABASE_NOT_NULL_CONSTRAINT_VIOLATION'
  | 'DATABASE_CHECK_CONSTRAINT_VIOLATION'
  | 'DATABASE_DEADLOCK_DETECTED'
  | 'DATABASE_LOCK_TIMEOUT'
  | 'DATABASE_SERIALIZATION_FAILURE'
  | 'DATABASE_MIGRATION_FAILED'
  | 'DATABASE_MIGRATION_ROLLBACK_FAILED'
  | 'DATABASE_SCHEMA_SYNC_FAILED'
  | 'DATABASE_SCHEMA_NOT_FOUND'
  | 'DATABASE_TABLE_NOT_FOUND'
  | 'DATABASE_COLUMN_NOT_FOUND'
  | 'DATABASE_CONFIGURATION_INVALID'
  | 'DATABASE_DRIVER_ERROR'
  | 'DATABASE_HEALTH_CHECK_FAILED'
  | 'DATABASE_UNKNOWN_ERROR'
)[];
export declare function isDatabaseErrorCode(
  value: unknown,
): value is DatabaseErrorCode;
