/**
 * User domain error codes.
 *
 * Use:
 * - `AuthErrorCode` for login, passwords, tokens, sessions, and email verification.
 * - `CommonErrorCode` for shared validation, request, and infrastructure failures.
 * - `UserErrorCode` for user, profile, settings, preferences, consent, and onboarding failures.
 */
export declare const UserErrorCode: {
  readonly USER_NOT_FOUND: 'USER_NOT_FOUND';
  readonly USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS';
  readonly USER_DISABLED: 'USER_DISABLED';
  readonly USER_SUSPENDED: 'USER_SUSPENDED';
  readonly USER_DELETED: 'USER_DELETED';
  readonly USER_LOCKED: 'USER_LOCKED';
  readonly USER_UNAUTHORIZED: 'USER_UNAUTHORIZED';
  readonly USER_FORBIDDEN: 'USER_FORBIDDEN';
  readonly USER_OWNERSHIP_REQUIRED: 'USER_OWNERSHIP_REQUIRED';
  readonly USER_PERMISSION_DENIED: 'USER_PERMISSION_DENIED';
  readonly INVALID_USER_ID: 'INVALID_USER_ID';
  readonly USER_ID_REQUIRED: 'USER_ID_REQUIRED';
  readonly USERNAME_REQUIRED: 'USERNAME_REQUIRED';
  readonly USERNAME_INVALID: 'USERNAME_INVALID';
  readonly USERNAME_TOO_SHORT: 'USERNAME_TOO_SHORT';
  readonly USERNAME_TOO_LONG: 'USERNAME_TOO_LONG';
  readonly USERNAME_RESERVED: 'USERNAME_RESERVED';
  readonly USERNAME_TAKEN: 'USERNAME_TAKEN';
  readonly USERNAME_CHANGE_NOT_ALLOWED: 'USERNAME_CHANGE_NOT_ALLOWED';
  readonly DISPLAY_NAME_INVALID: 'DISPLAY_NAME_INVALID';
  readonly DISPLAY_NAME_TOO_SHORT: 'DISPLAY_NAME_TOO_SHORT';
  readonly DISPLAY_NAME_TOO_LONG: 'DISPLAY_NAME_TOO_LONG';
  readonly USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND';
  readonly USER_PROFILE_ALREADY_EXISTS: 'USER_PROFILE_ALREADY_EXISTS';
  readonly INVALID_PROFILE_PAYLOAD: 'INVALID_PROFILE_PAYLOAD';
  readonly PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED';
  readonly USER_SETTINGS_NOT_FOUND: 'USER_SETTINGS_NOT_FOUND';
  readonly INVALID_SETTINGS_PAYLOAD: 'INVALID_SETTINGS_PAYLOAD';
  readonly SETTINGS_UPDATE_FAILED: 'SETTINGS_UPDATE_FAILED';
  readonly USER_PREFERENCES_NOT_FOUND: 'USER_PREFERENCES_NOT_FOUND';
  readonly INVALID_PREFERENCES_PAYLOAD: 'INVALID_PREFERENCES_PAYLOAD';
  readonly PREFERENCES_UPDATE_FAILED: 'PREFERENCES_UPDATE_FAILED';
  readonly USER_CONSENT_NOT_FOUND: 'USER_CONSENT_NOT_FOUND';
  readonly INVALID_CONSENT_PAYLOAD: 'INVALID_CONSENT_PAYLOAD';
  readonly CONSENT_UPDATE_FAILED: 'CONSENT_UPDATE_FAILED';
  readonly INVALID_AVATAR_URL: 'INVALID_AVATAR_URL';
  readonly AVATAR_UPLOAD_FAILED: 'AVATAR_UPLOAD_FAILED';
  readonly AVATAR_DELETE_FAILED: 'AVATAR_DELETE_FAILED';
  readonly AVATAR_TOO_LARGE: 'AVATAR_TOO_LARGE';
  readonly AVATAR_UNSUPPORTED_TYPE: 'AVATAR_UNSUPPORTED_TYPE';
  readonly ONBOARDING_REQUIRED: 'ONBOARDING_REQUIRED';
  readonly ONBOARDING_STATE_INVALID: 'ONBOARDING_STATE_INVALID';
  readonly ONBOARDING_STEP_INVALID: 'ONBOARDING_STEP_INVALID';
  readonly ONBOARDING_ALREADY_COMPLETED: 'ONBOARDING_ALREADY_COMPLETED';
  readonly ONBOARDING_UPDATE_FAILED: 'ONBOARDING_UPDATE_FAILED';
  readonly USER_SERVICE_UNAVAILABLE: 'USER_SERVICE_UNAVAILABLE';
  readonly USER_CONFIGURATION_INVALID: 'USER_CONFIGURATION_INVALID';
  readonly USER_RATE_LIMITED: 'USER_RATE_LIMITED';
  readonly USER_UNKNOWN_ERROR: 'USER_UNKNOWN_ERROR';
};
export type UserErrorCode = (typeof UserErrorCode)[keyof typeof UserErrorCode];
export declare const UserErrorCodeValues: (
  | 'USERNAME_REQUIRED'
  | 'USERNAME_INVALID'
  | 'USERNAME_TOO_SHORT'
  | 'USERNAME_TOO_LONG'
  | 'USER_NOT_FOUND'
  | 'USER_ALREADY_EXISTS'
  | 'USER_DISABLED'
  | 'USER_SUSPENDED'
  | 'USER_DELETED'
  | 'USER_LOCKED'
  | 'USER_UNAUTHORIZED'
  | 'USER_FORBIDDEN'
  | 'USER_OWNERSHIP_REQUIRED'
  | 'USER_PERMISSION_DENIED'
  | 'INVALID_USER_ID'
  | 'USER_ID_REQUIRED'
  | 'USERNAME_RESERVED'
  | 'USERNAME_TAKEN'
  | 'USERNAME_CHANGE_NOT_ALLOWED'
  | 'DISPLAY_NAME_INVALID'
  | 'DISPLAY_NAME_TOO_SHORT'
  | 'DISPLAY_NAME_TOO_LONG'
  | 'USER_PROFILE_NOT_FOUND'
  | 'USER_PROFILE_ALREADY_EXISTS'
  | 'INVALID_PROFILE_PAYLOAD'
  | 'PROFILE_UPDATE_FAILED'
  | 'USER_SETTINGS_NOT_FOUND'
  | 'INVALID_SETTINGS_PAYLOAD'
  | 'SETTINGS_UPDATE_FAILED'
  | 'USER_PREFERENCES_NOT_FOUND'
  | 'INVALID_PREFERENCES_PAYLOAD'
  | 'PREFERENCES_UPDATE_FAILED'
  | 'USER_CONSENT_NOT_FOUND'
  | 'INVALID_CONSENT_PAYLOAD'
  | 'CONSENT_UPDATE_FAILED'
  | 'INVALID_AVATAR_URL'
  | 'AVATAR_UPLOAD_FAILED'
  | 'AVATAR_DELETE_FAILED'
  | 'AVATAR_TOO_LARGE'
  | 'AVATAR_UNSUPPORTED_TYPE'
  | 'ONBOARDING_REQUIRED'
  | 'ONBOARDING_STATE_INVALID'
  | 'ONBOARDING_STEP_INVALID'
  | 'ONBOARDING_ALREADY_COMPLETED'
  | 'ONBOARDING_UPDATE_FAILED'
  | 'USER_SERVICE_UNAVAILABLE'
  | 'USER_CONFIGURATION_INVALID'
  | 'USER_RATE_LIMITED'
  | 'USER_UNKNOWN_ERROR'
)[];
export declare function isUserErrorCode(value: unknown): value is UserErrorCode;
