// libs/core/src/enumns/system/errors/user-error.enum.ts

/**
 * User domain error codes.
 *
 * Use:
 * - `AuthErrorCode` for login, passwords, tokens, sessions, and email verification.
 * - `CommonErrorCode` for shared validation, request, and infrastructure failures.
 * - `UserErrorCode` for user, profile, settings, preferences, consent, and onboarding failures.
 */
export const UserErrorCode = {
  // User lifecycle.
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_DISABLED: 'USER_DISABLED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_DELETED: 'USER_DELETED',
  USER_LOCKED: 'USER_LOCKED',

  // Access and ownership.
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',
  USER_FORBIDDEN: 'USER_FORBIDDEN',
  USER_OWNERSHIP_REQUIRED: 'USER_OWNERSHIP_REQUIRED',
  USER_PERMISSION_DENIED: 'USER_PERMISSION_DENIED',

  // User identity.
  INVALID_USER_ID: 'INVALID_USER_ID',
  USER_ID_REQUIRED: 'USER_ID_REQUIRED',

  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  USERNAME_INVALID: 'USERNAME_INVALID',
  USERNAME_TOO_SHORT: 'USERNAME_TOO_SHORT',
  USERNAME_TOO_LONG: 'USERNAME_TOO_LONG',
  USERNAME_RESERVED: 'USERNAME_RESERVED',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  USERNAME_CHANGE_NOT_ALLOWED: 'USERNAME_CHANGE_NOT_ALLOWED',

  DISPLAY_NAME_INVALID: 'DISPLAY_NAME_INVALID',
  DISPLAY_NAME_TOO_SHORT: 'DISPLAY_NAME_TOO_SHORT',
  DISPLAY_NAME_TOO_LONG: 'DISPLAY_NAME_TOO_LONG',

  // Profile.
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  USER_PROFILE_ALREADY_EXISTS: 'USER_PROFILE_ALREADY_EXISTS',
  INVALID_PROFILE_PAYLOAD: 'INVALID_PROFILE_PAYLOAD',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',

  // Settings.
  USER_SETTINGS_NOT_FOUND: 'USER_SETTINGS_NOT_FOUND',
  INVALID_SETTINGS_PAYLOAD: 'INVALID_SETTINGS_PAYLOAD',
  SETTINGS_UPDATE_FAILED: 'SETTINGS_UPDATE_FAILED',

  // Preferences.
  USER_PREFERENCES_NOT_FOUND: 'USER_PREFERENCES_NOT_FOUND',
  INVALID_PREFERENCES_PAYLOAD: 'INVALID_PREFERENCES_PAYLOAD',
  PREFERENCES_UPDATE_FAILED: 'PREFERENCES_UPDATE_FAILED',

  // Consent.
  USER_CONSENT_NOT_FOUND: 'USER_CONSENT_NOT_FOUND',
  INVALID_CONSENT_PAYLOAD: 'INVALID_CONSENT_PAYLOAD',
  CONSENT_UPDATE_FAILED: 'CONSENT_UPDATE_FAILED',

  // Avatar.
  INVALID_AVATAR_URL: 'INVALID_AVATAR_URL',
  AVATAR_UPLOAD_FAILED: 'AVATAR_UPLOAD_FAILED',
  AVATAR_DELETE_FAILED: 'AVATAR_DELETE_FAILED',
  AVATAR_TOO_LARGE: 'AVATAR_TOO_LARGE',
  AVATAR_UNSUPPORTED_TYPE: 'AVATAR_UNSUPPORTED_TYPE',

  // Onboarding.
  ONBOARDING_REQUIRED: 'ONBOARDING_REQUIRED',
  ONBOARDING_STATE_INVALID: 'ONBOARDING_STATE_INVALID',
  ONBOARDING_STEP_INVALID: 'ONBOARDING_STEP_INVALID',
  ONBOARDING_ALREADY_COMPLETED: 'ONBOARDING_ALREADY_COMPLETED',
  ONBOARDING_UPDATE_FAILED: 'ONBOARDING_UPDATE_FAILED',

  // Service failures.
  USER_SERVICE_UNAVAILABLE: 'USER_SERVICE_UNAVAILABLE',
  USER_CONFIGURATION_INVALID: 'USER_CONFIGURATION_INVALID',
  USER_RATE_LIMITED: 'USER_RATE_LIMITED',
  USER_UNKNOWN_ERROR: 'USER_UNKNOWN_ERROR',
} as const;

export type UserErrorCode =
  (typeof UserErrorCode)[keyof typeof UserErrorCode];

export const UserErrorCodeValues = Object.values(UserErrorCode);

export function isUserErrorCode(value: unknown): value is UserErrorCode {
  return (
    typeof value === 'string' &&
    UserErrorCodeValues.includes(value as UserErrorCode)
  );
}