packages:
  - tools/*
autoInstallPeers: true
resolvePeersFromWorkspaceRoot: true
dedupePeerDependents: true
dedupeDirectDeps: true
allowBuilds:
  "@swc/core": true
  esbuild: true
  nx: true
  sharp: true
  unrs-resolver: true
  workerd: true
overrides:
  "@opentelemetry/core": 2.8.0
