apiVersion: v1
kind: Namespace
metadata:
  name: kubelet-serving-cert-approver
  labels:
    app.kubernetes.io/name: kubelet-serving-cert-approver
    app.kubernetes.io/instance: kubelet-serving-cert-approver
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: aerealith-platform
    app.kubernetes.io/managed-by: flux

    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    aerealith.com/description: Approves validated kubelet serving certificate signing requests
