export const SYSTEM_PERMISSION_KEYS = [
  'account.read',
  'account.update',
  'authorization.permissions.read',
  'authorization.permissions.manage',
  'authorization.roles.read',
  'authorization.roles.create',
  'authorization.roles.update',
  'authorization.roles.delete',
  'authorization.roles.assign',
  'authorization.roles.revoke',
  'authorization.roles.system.manage',
  'authorization.assignments.read',
  'authorization.assignments.manage',
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'users.suspend',
  'users.impersonate',
  'users.manage',
  'sessions.read',
  'sessions.revoke',
  'sessions.revoke_all',
  'roles.read',
  'roles.create',
  'roles.update',
  'roles.delete',
  'roles.assign',
  'roles.revoke',
  'permissions.read',
  'permissions.assign',
  'permissions.revoke',
  'audit.read',
  'projects.read',
  'projects.create',
  'projects.update',
  'projects.delete',
  'organizations.read',
  'organizations.create',
  'organizations.update',
  'organizations.delete',
  'discord.guild.read',
  'discord.guild.manage',
  'notifications.read',
  'notifications.manage',
  'ai.assistant.use',
  'ai.assistant.manage',
  'documentation.read',
  'documentation.manage',
  'billing.read',
  'billing.manage',
] as const;

export type SystemPermissionKey = (typeof SYSTEM_PERMISSION_KEYS)[number];

export const SYSTEM_ROLE_KEYS = [
  'user',
  'support_agent',
  'security_administrator',
  'platform_administrator',
  'platform_owner',
  'service',
] as const;

export type SystemRoleKey = (typeof SYSTEM_ROLE_KEYS)[number];
