profile: ambient

# Keep Istiod highly available.
autoscaleEnabled: true
autoscaleMin: 2
autoscaleMax: 5

# Never place both Istiod replicas on the same node.
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - istiod
        topologyKey: kubernetes.io/hostname

global:
  logAsJson: true
