apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aerealith
  namespace: flux-system
spec:
  interval: 1m

  url: https://github.com/SinLess-Games/Aerealith.git

  ref:
    branch: master

  timeout: 60s
