apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - network-policies.yaml

  - source-controller.yaml
  - kustomize-controller.yaml
  - helm-controller.yaml
  - notification-controller.yaml

  - git-repository.yaml
  - cluster-kustomization.yaml
