apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/component: service-mesh
    app.kubernetes.io/part-of: aerealith-platform
    app.kubernetes.io/managed-by: flux

    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest

    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    aerealith.com/description: Istio Ambient service mesh control plane and node infrastructure
