apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/component: repository
    app.kubernetes.io/part-of: aerealith-platform
    app.kubernetes.io/managed-by: flux
spec:
  interval: 12h
  url: https://blob.istio.io/istio-release/charts
