apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cilium.yaml
  - falco.yaml
  - grafana.yaml
  - kyverno.yaml
  - opentelemetry.yaml
  - openbao.yaml
  - prometheus-community.yaml
  - metrics-server.yaml
  - istio.yaml
  - kiali.yaml
