import {
  useEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
} from 'react';

import { cn } from '@aerealith-ai/ui';
import { NavLink, useLocation } from 'react-router';

import type {
  DocsAudience,
  DocsTree,
  DocsTreeNode,
} from '../../../../lib/docs-source';

export interface DocsSidebarProps extends Omit<
  ComponentPropsWithoutRef<'aside'>,
  'children'
> {
  /**
   * Active documentation audience.
   */
  audience: DocsAudience;

  /**
   * Navigation tree generated by `getDocsTree()`.
   */
  tree: DocsTree;

  /**
   * Controls the mobile sidebar dialog.
   */
  mobileOpen?: boolean;

  /**
   * Called when the mobile sidebar should close.
   */
  onMobileClose?: () => void;

  /**
   * Called when the native dialog is dismissed with Escape.
   */
  onMobileEscape?: () => void;

  /**
   * Accessible ID referenced by the mobile header trigger.
   */
  mobileId?: string;

  /**
   * Label shown above the navigation tree.
   */
  label?: string;

  /**
   * Additional classes applied to the desktop sidebar.
   */
  desktopClassName?: string;

  /**
   * Additional classes applied to the mobile sidebar panel.
   */
  mobileClassName?: string;
}

/**
 * Responsive documentation navigation.
 *
 * The desktop sidebar is sticky and permanently visible on large screens.
 * The mobile version uses a native modal dialog with a proper interactive
 * backdrop.
 */
export function DocsSidebar({
  audience,
  className,
  desktopClassName,
  label,
  mobileClassName,
  mobileId = 'docs-mobile-sidebar',
  mobileOpen = false,
  onMobileClose,
  onMobileEscape,
  tree,
  ...props
}: Readonly<DocsSidebarProps>) {
  const resolvedLabel = label ?? getAudienceLabel(audience);

  return (
    <>
      <aside
        {...props}
        className={cn('hidden min-w-0 lg:block', className, desktopClassName)}
        data-audience={audience}
        data-slot="docs-sidebar"
      >
        <div
          className={cn(
            'sticky top-28 max-h-[calc(100vh-8rem)]',
            'overflow-y-auto py-8 pr-2',
            'scrollbar-thin',
          )}
        >
          <DocsSidebarContent
            audience={audience}
            label={resolvedLabel}
            tree={tree}
          />
        </div>
      </aside>

      <DocsMobileSidebar
        audience={audience}
        id={mobileId}
        isOpen={mobileOpen}
        label={resolvedLabel}
        onClose={onMobileClose}
        onEscape={onMobileEscape}
        panelClassName={mobileClassName}
        tree={tree}
      />
    </>
  );
}

interface DocsMobileSidebarProps {
  audience: DocsAudience;
  id: string;
  isOpen: boolean;
  label: string;
  onClose?: () => void;
  onEscape?: () => void;
  panelClassName?: string;
  tree: DocsTree;
}

function DocsMobileSidebar({
  audience,
  id,
  isOpen,
  label,
  onClose,
  onEscape,
  panelClassName,
  tree,
}: Readonly<DocsMobileSidebarProps>) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const closeButtonRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    const dialog = dialogRef.current;

    if (!dialog || !isOpen) return;

    if (!dialog.open) {
      dialog.showModal();
    }

    const focusFrame = window.requestAnimationFrame(() => {
      closeButtonRef.current?.focus();
    });

    return () => {
      window.cancelAnimationFrame(focusFrame);

      if (dialog.open) {
        dialog.close();
      }
    };
  }, [isOpen]);

  if (!isOpen) return null;

  const closeSidebar = () => {
    onClose?.();
  };

  return (
    <dialog
      ref={dialogRef}
      id={id}
      aria-label={`${label} navigation`}
      className={cn(
        'fixed inset-0 m-0 h-dvh max-h-none w-full max-w-none',
        'overflow-hidden border-0 bg-transparent p-0',
        'backdrop:bg-black/55',
        'backdrop:backdrop-blur-sm',
        'lg:hidden',
      )}
      data-slot="docs-mobile-sidebar"
      onCancel={(event) => {
        event.preventDefault();
        onEscape?.() ?? closeSidebar();
      }}
    >
      <button
        type="button"
        aria-label="Close documentation navigation"
        className="absolute inset-0 cursor-default bg-transparent"
        onClick={closeSidebar}
      />

      <aside
        className={cn(
          'relative z-10 flex h-full w-[min(22rem,88vw)]',
          'flex-col border-r border-[var(--ae-border)]',
          'bg-[color-mix(in_srgb,var(--ae-background)_96%,transparent)]',
          'shadow-[24px_0_70px_rgba(0,0,0,0.35)]',
          'backdrop-blur-2xl',
          panelClassName,
        )}
        data-audience={audience}
      >
        <header
          className={cn(
            'flex min-h-16 items-center justify-between gap-3',
            'border-b border-[var(--ae-border)] px-4',
          )}
        >
          <div className="min-w-0">
            <div className="truncate text-sm font-semibold text-[var(--ae-foreground)]">
              {label}
            </div>

            <div className="text-xs text-[var(--ae-foreground-muted)]">
              Documentation navigation
            </div>
          </div>

          <button
            ref={closeButtonRef}
            type="button"
            aria-label="Close documentation navigation"
            className={cn(
              'grid size-10 shrink-0 place-items-center rounded-lg',
              'text-[var(--ae-foreground-muted)]',
              'transition duration-150',
              'hover:bg-[var(--ae-surface)]',
              'hover:text-[var(--ae-foreground)]',
              'focus-visible:outline-2',
              'focus-visible:outline-offset-2',
              'focus-visible:outline-[var(--ae-accent)]',
            )}
            onClick={closeSidebar}
          >
            <CloseIcon />
          </button>
        </header>

        <div className="flex-1 overflow-y-auto p-4">
          <DocsSidebarContent
            audience={audience}
            label={label}
            onNavigate={closeSidebar}
            tree={tree}
          />
        </div>
      </aside>
    </dialog>
  );
}

interface DocsSidebarContentProps {
  audience: DocsAudience;
  label: string;
  onNavigate?: () => void;
  tree: DocsTree;
}

function DocsSidebarContent({
  audience,
  label,
  onNavigate,
  tree,
}: Readonly<DocsSidebarContentProps>) {
  const { pathname } = useLocation();
  const isEmpty = tree.rootPage === undefined && tree.children.length === 0;

  return (
    <nav
      aria-label={`${label} navigation`}
      className={cn(
        'rounded-2xl border border-[var(--ae-border)] p-3',
        'bg-[color-mix(in_srgb,var(--ae-background)_26%,transparent)]',
        'shadow-[0_18px_50px_rgba(0,0,0,0.22)] backdrop-blur-sm',
      )}
      data-slot="docs-sidebar-navigation"
    >
      <div className="mb-4 px-2">
        <div
          className={cn(
            'text-xs font-semibold tracking-[0.16em] uppercase',
            'text-[var(--ae-foreground-muted)]',
          )}
        >
          {label}
        </div>
      </div>

      {!isEmpty ? (
        <ul key={pathname} className="space-y-1">
          {tree.rootPage ? (
            <DocsNavigationNode
              key={`${audience}-root`}
              depth={0}
              node={{
                segment: audience,
                title: tree.rootPage.title,
                url: tree.rootPage.url,
                page: tree.rootPage,
                children: tree.children,
              }}
              onNavigate={onNavigate}
            />
          ) : (
            tree.children.map((node) => (
              <DocsNavigationNode
                key={`${audience}-${node.segment}`}
                depth={0}
                node={node}
                onNavigate={onNavigate}
              />
            ))
          )}
        </ul>
      ) : (
        <DocsSidebarEmptyState audience={audience} />
      )}
    </nav>
  );
}

interface DocsNavigationNodeProps {
  depth: number;
  node: DocsTreeNode;
  onNavigate?: () => void;
}

function DocsNavigationNode({
  depth,
  node,
  onNavigate,
}: Readonly<DocsNavigationNodeProps>) {
  const hasChildren = node.children.length > 0;
  const isFolder = node.page?.isIndex === true || hasChildren;
  const { pathname } = useLocation();
  const containsActivePage = isPathInNode(node, pathname);
  const [isExpanded, setIsExpanded] = useState(containsActivePage);

  return (
    <li data-depth={depth}>
      <div className={cn(hasChildren && 'flex min-w-0 items-center gap-1')}>
        {hasChildren ? (
          <button
            type="button"
            aria-expanded={isExpanded}
            aria-label={`${isExpanded ? 'Collapse' : 'Expand'} ${node.title}`}
            className={cn(
              'grid size-9 shrink-0 place-items-center rounded-lg',
              'border border-transparent text-[var(--ae-foreground)]',
              'bg-[color-mix(in_srgb,var(--ae-background)_28%,transparent)]',
              'transition hover:border-[var(--ae-border)]',
              'hover:bg-[color-mix(in_srgb,var(--ae-background)_52%,transparent)]',
              'focus-visible:outline-2 focus-visible:outline-offset-1',
              'focus-visible:outline-[var(--ae-accent)]',
            )}
            onClick={() => setIsExpanded((expanded) => !expanded)}
          >
            <ChevronRightIcon
              className={cn(
                'size-4 transition-transform',
                isExpanded && 'rotate-90',
              )}
            />
          </button>
        ) : null}

        {node.url ? (
          <DocsNavigationLink
            badge={node.page?.badge}
            className={hasChildren ? 'min-w-0 flex-1' : undefined}
            end
            icon={isFolder ? 'folder' : 'page'}
            onNavigate={onNavigate}
            showArrow={!hasChildren}
            title={node.title}
            url={node.url}
          />
        ) : (
          <DocsNavigationGroupLabel
            className={hasChildren ? 'min-w-0 flex-1 py-2' : undefined}
            title={node.title}
          />
        )}
      </div>

      {hasChildren && isExpanded ? (
        <ul
          className={cn(
            'mt-1 space-y-1 border-l-2',
            'border-[color-mix(in_srgb,var(--ae-accent)_32%,var(--ae-border))]',
            depth === 0 ? 'ml-4 pl-4' : 'ml-3 pl-3',
          )}
        >
          {node.children.map((child) => (
            <DocsNavigationNode
              key={`${node.segment}-${child.segment}`}
              depth={depth + 1}
              node={child}
              onNavigate={onNavigate}
            />
          ))}
        </ul>
      ) : null}
    </li>
  );
}

interface DocsNavigationLinkProps {
  badge?: string;
  className?: string;
  end?: boolean;
  icon?: 'folder' | 'page';
  onNavigate?: () => void;
  showArrow?: boolean;
  title: string;
  url: string;
}

function DocsNavigationLink({
  badge,
  className,
  end,
  icon = 'page',
  onNavigate,
  showArrow = true,
  title,
  url,
}: Readonly<DocsNavigationLinkProps>) {
  return (
    <NavLink
      to={url}
      end={end}
      onClick={onNavigate}
      style={{ color: 'var(--ae-foreground)' }}
      className={({ isActive }) =>
        cn(
          'group flex min-h-10 items-center gap-2',
          'rounded-lg px-3 py-2',
          'text-sm font-medium transition duration-150',
          'focus-visible:outline-2',
          'focus-visible:outline-offset-1',
          'focus-visible:outline-[var(--ae-accent)]',
          isActive
            ? cn(
                'border border-[color-mix(in_srgb,var(--ae-accent)_55%,transparent)]',
                'bg-[color-mix(in_srgb,var(--ae-background)_38%,var(--ae-accent))]',
                'text-[var(--ae-foreground)]',
                'shadow-[inset_3px_0_0_var(--ae-accent),0_5px_18px_rgba(0,0,0,0.2)]',
              )
            : cn(
                'border border-transparent',
                'bg-[color-mix(in_srgb,var(--ae-background)_20%,transparent)]',
                'text-[var(--ae-foreground)]',
                'hover:border-[var(--ae-border)]',
                'hover:bg-[color-mix(in_srgb,var(--ae-background)_48%,transparent)]',
                'hover:text-[var(--ae-foreground)]',
              ),
          className,
        )
      }
    >
      {({ isActive }) => (
        <>
          {icon === 'folder' ? (
            <FolderIcon
              className={cn(
                'size-4 shrink-0',
                isActive
                  ? 'text-[var(--ae-foreground)]'
                  : 'text-[var(--ae-foreground-muted)]',
              )}
            />
          ) : (
            <PageIcon
              className={cn(
                'size-4 shrink-0',
                isActive
                  ? 'text-[var(--ae-foreground)]'
                  : 'text-[var(--ae-foreground-muted)]',
              )}
            />
          )}

          <span className="min-w-0 flex-1 truncate">{title}</span>

          {badge ? (
            <span
              className={cn(
                'inline-flex min-h-5 shrink-0 items-center rounded-full',
                'border border-[var(--ae-border)] px-1.5',
                'text-[0.625rem] font-semibold',
                isActive
                  ? 'text-[var(--ae-foreground)]'
                  : 'text-[var(--ae-foreground-muted)]',
              )}
            >
              {badge}
            </span>
          ) : null}

          {showArrow ? (
            <ChevronRightIcon
              className={cn(
                'size-4 shrink-0 opacity-0 transition',
                'group-hover:translate-x-0.5',
                'group-hover:opacity-60',
                isActive && 'opacity-65',
              )}
            />
          ) : null}
        </>
      )}
    </NavLink>
  );
}

function DocsNavigationGroupLabel({
  className,
  title,
}: Readonly<{ className?: string; title: string }>) {
  return (
    <div
      className={cn(
        'px-3 pt-4 pb-1',
        'text-xs font-semibold tracking-wide uppercase',
        'text-[var(--ae-foreground)]',
        className,
      )}
    >
      {title}
    </div>
  );
}

function DocsSidebarEmptyState({
  audience,
}: Readonly<{ audience: DocsAudience }>) {
  return (
    <div
      className={cn(
        'rounded-xl border border-dashed p-4',
        'border-[var(--ae-border)]',
      )}
    >
      <div className="text-sm font-semibold text-[var(--ae-foreground)]">
        No pages available
      </div>

      <p className="mt-1 text-sm leading-6 text-[var(--ae-foreground-muted)]">
        No {audience} documentation pages are currently available.
      </p>
    </div>
  );
}

function getAudienceLabel(audience: DocsAudience): string {
  return audience === 'developer'
    ? 'Developer documentation'
    : 'User documentation';
}

function isPathInNode(node: DocsTreeNode, pathname: string): boolean {
  if (node.url === pathname) return true;

  return node.children.some((child) => isPathInNode(child, pathname));
}

function CloseIcon() {
  return (
    <svg aria-hidden="true" className="size-5" fill="none" viewBox="0 0 24 24">
      <path
        d="m6 6 12 12M18 6 6 18"
        stroke="currentColor"
        strokeLinecap="round"
        strokeWidth="1.75"
      />
    </svg>
  );
}

function ChevronRightIcon({ className }: Readonly<{ className?: string }>) {
  return (
    <svg
      aria-hidden="true"
      className={className}
      fill="none"
      viewBox="0 0 24 24"
    >
      <path
        d="m9 6 6 6-6 6"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.75"
      />
    </svg>
  );
}

function FolderIcon({ className }: Readonly<{ className?: string }>) {
  return (
    <svg
      aria-hidden="true"
      className={className}
      fill="none"
      viewBox="0 0 24 24"
    >
      <path
        d="M3.75 7.75h6l1.5 2h9v7.5a2 2 0 0 1-2 2H5.75a2 2 0 0 1-2-2v-9.5Zm0 0v-.5a2 2 0 0 1 2-2h3.1l1.5 2.5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.6"
      />
    </svg>
  );
}

function PageIcon({ className }: Readonly<{ className?: string }>) {
  return (
    <svg
      aria-hidden="true"
      className={className}
      fill="none"
      viewBox="0 0 24 24"
    >
      <path
        d="M7 3.75h6.25L17 7.5v12.75H7V3.75Zm6 0V8h4"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.6"
      />
    </svg>
  );
}

export default DocsSidebar;
