import {
  useDeferredValue,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type KeyboardEvent as ReactKeyboardEvent,
} from 'react'

import { cn } from '@aerealith-ai/ui'
import { Link, useLocation, useNavigate } from 'react-router'

import {
  getAudienceFromDocsUrl,
  searchDocs,
  type DocsAudience,
  type DocsSearchResult,
} from '../../../../lib/docs-source'

export interface DocsSearchProps extends Omit<
  ComponentPropsWithoutRef<'div'>,
  'children'
> {
  /**
   * Explicit documentation audience to search.
   *
   * When omitted, the audience is derived from the current documentation URL.
   */
  audience?: DocsAudience

  /**
   * Search all documentation rather than restricting results to the current
   * audience.
   */
  searchAllAudiences?: boolean

  /**
   * Maximum number of search results displayed.
   */
  maxResults?: number

  /**
   * Search input placeholder.
   */
  placeholder?: string

  /**
   * Visible label inside the search trigger.
   */
  triggerLabel?: string

  /**
   * Accessible title displayed inside the search dialog.
   */
  dialogTitle?: string

  /**
   * Message displayed when no documents match the query.
   */
  emptyMessage?: string

  /**
   * Render a smaller trigger suitable for compact headers.
   */
  compact?: boolean

  /**
   * Display the Ctrl/Cmd + K keyboard shortcut.
   */
  showShortcut?: boolean

  /**
   * Enable the global Ctrl/Cmd + K keyboard shortcut.
   */
  enableShortcut?: boolean
}

/**
 * Audience-aware documentation search.
 *
 * Search is performed against the browser-safe metadata generated by
 * Fumadocs and normalized by `docs-source.ts`.
 */
export function DocsSearch({
  audience,
  className,
  compact = false,
  dialogTitle = 'Search documentation',
  emptyMessage = 'No documentation matched your search.',
  enableShortcut = true,
  maxResults = 12,
  placeholder = 'Search guides, APIs, and concepts…',
  searchAllAudiences = false,
  showShortcut = true,
  triggerLabel = 'Search documentation',
  ...props
}: Readonly<DocsSearchProps>) {
  const location = useLocation()
  const navigate = useNavigate()

  const dialogRef = useRef<HTMLDialogElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  const titleId = useId()
  const resultsId = useId()
  const statusId = useId()

  const [isOpen, setIsOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [activeIndex, setActiveIndex] = useState(0)

  const deferredQuery = useDeferredValue(query)

  const currentAudience = audience ?? getAudienceFromDocsUrl(location.pathname)

  const searchAudience = searchAllAudiences ? undefined : currentAudience

  const results = useMemo(
    () =>
      searchDocs(deferredQuery, {
        audience: searchAudience,
        limit: maxResults,
      }),
    [deferredQuery, maxResults, searchAudience],
  )

  const normalizedActiveIndex =
    results.length === 0
      ? -1
      : Math.min(Math.max(activeIndex, 0), results.length - 1)

  const activeResult =
    normalizedActiveIndex >= 0 ? results.at(normalizedActiveIndex) : undefined

  useEffect(() => {
    if (!enableShortcut) return

    const openWithKeyboardShortcut = (event: KeyboardEvent) => {
      const isSearchShortcut =
        (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k'

      if (!isSearchShortcut || isEditableTarget(event.target)) {
        return
      }

      event.preventDefault()
      setActiveIndex(0)
      setIsOpen(true)
    }

    window.addEventListener('keydown', openWithKeyboardShortcut)

    return () => {
      window.removeEventListener('keydown', openWithKeyboardShortcut)
    }
  }, [enableShortcut])

  useEffect(() => {
    const dialog = dialogRef.current

    if (!dialog || !isOpen) return

    if (!dialog.open) {
      dialog.showModal()
    }

    const focusFrame = window.requestAnimationFrame(() => {
      inputRef.current?.focus()
    })

    return () => {
      window.cancelAnimationFrame(focusFrame)

      if (dialog.open) {
        dialog.close()
      }
    }
  }, [isOpen])

  const openSearch = () => {
    setActiveIndex(0)
    setIsOpen(true)
  }

  const closeSearch = () => {
    setIsOpen(false)
    setQuery('')
    setActiveIndex(0)
  }

  const navigateToResult = (result: DocsSearchResult | undefined) => {
    if (!result) return

    navigate(result.page.url)
    closeSearch()
  }

  const handleInputKeyDown = (event: ReactKeyboardEvent<HTMLInputElement>) => {
    if (results.length === 0) return

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault()

        setActiveIndex((currentIndex) => {
          const safeIndex = Math.min(
            Math.max(currentIndex, 0),
            results.length - 1,
          )

          return (safeIndex + 1) % results.length
        })
        break

      case 'ArrowUp':
        event.preventDefault()

        setActiveIndex((currentIndex) => {
          const safeIndex = Math.min(
            Math.max(currentIndex, 0),
            results.length - 1,
          )

          return (safeIndex - 1 + results.length) % results.length
        })
        break

      case 'Home':
        event.preventDefault()
        setActiveIndex(0)
        break

      case 'End':
        event.preventDefault()
        setActiveIndex(results.length - 1)
        break

      case 'Enter':
        event.preventDefault()
        navigateToResult(activeResult)
        break

      default:
        break
    }
  }

  return (
    <div
      {...props}
      className={cn('relative', className)}
      data-slot='docs-search'
    >
      <button
        type='button'
        aria-haspopup='dialog'
        aria-expanded={isOpen}
        className={cn(
          'group flex items-center rounded-xl border',
          'border-[var(--ae-border)]',
          'bg-[color-mix(in_srgb,var(--ae-surface)_68%,transparent)]',
          'text-[var(--ae-foreground-muted)]',
          'shadow-[inset_0_1px_0_rgba(255,255,255,0.035)]',
          'backdrop-blur-xl transition duration-150',
          'hover:border-[color-mix(in_srgb,var(--ae-accent)_40%,var(--ae-border))]',
          'hover:bg-[var(--ae-surface)]',
          'hover:text-[var(--ae-foreground)]',
          'focus-visible:outline-2',
          'focus-visible:outline-offset-2',
          'focus-visible:outline-[var(--ae-accent)]',
          compact ? 'min-h-10 gap-2 px-3' : 'min-h-11 min-w-56 gap-3 px-3.5',
        )}
        onClick={openSearch}
      >
        <SearchIcon className='size-4 shrink-0' />

        <span
          className={cn(
            'min-w-0 flex-1 truncate text-left font-medium',
            compact ? 'sr-only' : 'text-sm',
          )}
        >
          {triggerLabel}
        </span>

        {showShortcut ? <ShortcutKeys compact={compact} /> : null}
      </button>

      {isOpen ? (
        <dialog
          ref={dialogRef}
          aria-labelledby={titleId}
          aria-describedby={statusId}
          className={cn(
            'fixed inset-0 m-0 h-dvh max-h-none w-full max-w-none',
            'overflow-hidden border-0 bg-transparent p-0',
            'backdrop:bg-black/60',
            'backdrop:backdrop-blur-sm',
          )}
          onCancel={(event) => {
            event.preventDefault()
            closeSearch()
          }}
        >
          <button
            type='button'
            aria-label='Close documentation search'
            className='absolute inset-0 cursor-default bg-transparent'
            onClick={closeSearch}
          />

          <section
            className={cn(
              'relative z-10 mx-auto mt-[8vh] flex w-[calc(100%-2rem)]',
              'max-w-3xl flex-col overflow-hidden rounded-2xl border',
              'border-[var(--ae-border)]',
              'bg-[color-mix(in_srgb,var(--ae-background)_97%,transparent)]',
              'shadow-[0_35px_120px_rgba(0,0,0,0.55)]',
              'backdrop-blur-2xl sm:mt-[12vh]',
            )}
          >
            <header
              className={cn(
                'flex items-center justify-between gap-4',
                'border-b border-[var(--ae-border)] px-4 py-3',
                'sm:px-5',
              )}
            >
              <div className='min-w-0'>
                <h2
                  id={titleId}
                  className='truncate text-sm font-semibold text-[var(--ae-foreground)]'
                >
                  {dialogTitle}
                </h2>

                <p className='mt-0.5 text-xs text-[var(--ae-foreground-muted)]'>
                  {getSearchScopeLabel(searchAudience)}
                </p>
              </div>

              <button
                type='button'
                aria-label='Close documentation search'
                className={cn(
                  'grid size-9 shrink-0 place-items-center rounded-lg',
                  'text-[var(--ae-foreground-muted)]',
                  'transition duration-150',
                  'hover:bg-[var(--ae-surface)]',
                  'hover:text-[var(--ae-foreground)]',
                  'focus-visible:outline-2',
                  'focus-visible:outline-offset-2',
                  'focus-visible:outline-[var(--ae-accent)]',
                )}
                onClick={closeSearch}
              >
                <CloseIcon />
              </button>
            </header>

            <form
              role='search'
              className='border-b border-[var(--ae-border)] p-3 sm:p-4'
              onSubmit={(event) => {
                event.preventDefault()
                navigateToResult(activeResult)
              }}
            >
              <label className='sr-only' htmlFor={`${resultsId}-input`}>
                Search documentation
              </label>

              <div className='relative'>
                <SearchIcon
                  className={cn(
                    'pointer-events-none absolute top-1/2 left-4',
                    'size-5 -translate-y-1/2',
                    'text-[var(--ae-foreground-muted)]',
                  )}
                />

                <input
                  ref={inputRef}
                  id={`${resultsId}-input`}
                  type='search'
                  value={query}
                  placeholder={placeholder}
                  autoComplete='off'
                  spellCheck={false}
                  aria-controls={resultsId}
                  aria-describedby={statusId}
                  className={cn(
                    'min-h-13 w-full rounded-xl border py-3 pr-12 pl-12',
                    'border-[var(--ae-border)]',
                    'bg-[color-mix(in_srgb,var(--ae-surface)_72%,transparent)]',
                    'text-base text-[var(--ae-foreground)]',
                    'placeholder:text-[var(--ae-foreground-muted)]',
                    'transition duration-150',
                    'focus:border-[color-mix(in_srgb,var(--ae-accent)_55%,var(--ae-border))]',
                    'focus:outline-none',
                    'focus:ring-2',
                    'focus:ring-[color-mix(in_srgb,var(--ae-accent)_18%,transparent)]',
                  )}
                  onChange={(event) => {
                    setQuery(event.target.value)
                    setActiveIndex(0)
                  }}
                  onKeyDown={handleInputKeyDown}
                />

                {query.length > 0 ? (
                  <button
                    type='button'
                    aria-label='Clear documentation search'
                    className={cn(
                      'absolute top-1/2 right-3 grid size-8',
                      '-translate-y-1/2 place-items-center rounded-md',
                      'text-[var(--ae-foreground-muted)]',
                      'transition duration-150',
                      'hover:bg-[var(--ae-background)]',
                      'hover:text-[var(--ae-foreground)]',
                      'focus-visible:outline-2',
                      'focus-visible:outline-offset-1',
                      'focus-visible:outline-[var(--ae-accent)]',
                    )}
                    onClick={() => {
                      setQuery('')
                      setActiveIndex(0)
                      inputRef.current?.focus()
                    }}
                  >
                    <CloseIcon className='size-4' />
                  </button>
                ) : null}
              </div>
            </form>

            <div
              id={resultsId}
              className='max-h-[min(34rem,60vh)] overflow-y-auto p-2 sm:p-3'
            >
              {deferredQuery.trim().length === 0 ? (
                <SearchInstructions />
              ) : null}

              {deferredQuery.trim().length > 0 && results.length === 0 ? (
                <SearchEmptyState
                  message={emptyMessage}
                  query={deferredQuery}
                />
              ) : null}

              {results.length > 0 ? (
                <ul
                  aria-label='Documentation search results'
                  className='space-y-1'
                >
                  {results.map((result, index) => (
                    <SearchResultItem
                      key={result.page.url}
                      active={index === normalizedActiveIndex}
                      result={result}
                      onNavigate={closeSearch}
                      onSelect={() => setActiveIndex(index)}
                    />
                  ))}
                </ul>
              ) : null}
            </div>

            <footer
              className={cn(
                'flex flex-wrap items-center gap-x-5 gap-y-2',
                'border-t border-[var(--ae-border)] px-4 py-3',
                'text-xs text-[var(--ae-foreground-muted)]',
              )}
            >
              <SearchHint keys={['↑', '↓']} label='Navigate' />
              <SearchHint keys={['Enter']} label='Open' />
              <SearchHint keys={['Esc']} label='Close' />

              <span id={statusId} className='ml-auto' aria-live='polite'>
                {getResultsStatus(deferredQuery, results.length)}
              </span>
            </footer>
          </section>
        </dialog>
      ) : null}
    </div>
  )
}

interface SearchResultItemProps {
  active: boolean
  result: DocsSearchResult
  onNavigate: () => void
  onSelect: () => void
}

function SearchResultItem({
  active,
  onNavigate,
  onSelect,
  result,
}: Readonly<SearchResultItemProps>) {
  const { page } = result

  return (
    <li>
      <Link
        to={page.url}
        aria-current={active ? 'true' : undefined}
        className={cn(
          'group flex items-start gap-3 rounded-xl border px-3 py-3',
          'transition duration-150 sm:px-4',
          active
            ? cn(
                'border-[color-mix(in_srgb,var(--ae-accent)_38%,var(--ae-border))]',
                'bg-[color-mix(in_srgb,var(--ae-accent)_10%,transparent)]',
              )
            : cn(
                'border-transparent',
                'hover:border-[var(--ae-border)]',
                'hover:bg-[color-mix(in_srgb,var(--ae-surface)_72%,transparent)]',
              ),
          'focus-visible:outline-2',
          'focus-visible:outline-offset-1',
          'focus-visible:outline-[var(--ae-accent)]',
        )}
        onClick={onNavigate}
        onFocus={onSelect}
        onPointerMove={onSelect}
      >
        <span
          aria-hidden='true'
          className={cn(
            'mt-0.5 grid size-9 shrink-0 place-items-center rounded-lg',
            'border border-[var(--ae-border)]',
            'bg-[color-mix(in_srgb,var(--ae-background)_70%,transparent)]',
            active
              ? 'text-[var(--ae-accent)]'
              : 'text-[var(--ae-foreground-muted)]',
          )}
        >
          {page.audience === 'developer' ? (
            <DeveloperIcon />
          ) : (
            <UserGuideIcon />
          )}
        </span>

        <span className='min-w-0 flex-1'>
          <span className='flex flex-wrap items-center gap-2'>
            <span
              className={cn(
                'truncate text-sm font-semibold',
                active
                  ? 'text-[var(--ae-accent)]'
                  : 'text-[var(--ae-foreground)]',
              )}
            >
              {page.title}
            </span>

            <span
              className={cn(
                'inline-flex min-h-5 items-center rounded-full',
                'border border-[var(--ae-border)] px-2',
                'text-[0.625rem] font-semibold tracking-wide uppercase',
                'text-[var(--ae-foreground-muted)]',
              )}
            >
              {page.audience}
            </span>

            {page.badge ? (
              <span
                className={cn(
                  'inline-flex min-h-5 items-center rounded-full',
                  'bg-[color-mix(in_srgb,var(--ae-accent)_10%,transparent)]',
                  'px-2 text-[0.625rem] font-semibold',
                  'text-[var(--ae-accent)]',
                )}
              >
                {page.badge}
              </span>
            ) : null}
          </span>

          <span
            className={cn(
              'mt-1 block line-clamp-2 text-xs leading-5',
              'text-[var(--ae-foreground-muted)]',
            )}
          >
            {page.description}
          </span>

          <span
            className={cn(
              'mt-2 block truncate font-mono text-[0.6875rem]',
              'text-[color-mix(in_srgb,var(--ae-foreground-muted)_72%,transparent)]',
            )}
          >
            {page.url}
          </span>
        </span>

        <ArrowRightIcon
          className={cn(
            'mt-2 size-4 shrink-0 transition-transform',
            'text-[var(--ae-foreground-muted)]',
            'group-hover:translate-x-0.5',
            active && 'translate-x-0.5 text-[var(--ae-accent)]',
          )}
        />
      </Link>
    </li>
  )
}

function SearchInstructions() {
  return (
    <div
      className={cn(
        'flex min-h-48 flex-col items-center justify-center px-6',
        'py-10 text-center',
      )}
    >
      <span
        aria-hidden='true'
        className={cn(
          'grid size-12 place-items-center rounded-2xl border',
          'border-[var(--ae-border)]',
          'bg-[color-mix(in_srgb,var(--ae-surface)_72%,transparent)]',
          'text-[var(--ae-accent)]',
        )}
      >
        <SearchIcon className='size-6' />
      </span>

      <h3 className='mt-4 text-sm font-semibold text-[var(--ae-foreground)]'>
        Find documentation quickly
      </h3>

      <p className='mt-1 max-w-sm text-sm leading-6 text-[var(--ae-foreground-muted)]'>
        Search page titles, descriptions, headings, keywords, and documentation
        paths.
      </p>
    </div>
  )
}

interface SearchEmptyStateProps {
  message: string
  query: string
}

function SearchEmptyState({ message, query }: Readonly<SearchEmptyStateProps>) {
  return (
    <div
      className={cn(
        'flex min-h-48 flex-col items-center justify-center',
        'px-6 py-10 text-center',
      )}
    >
      <span
        aria-hidden='true'
        className={cn(
          'grid size-12 place-items-center rounded-2xl border',
          'border-[var(--ae-border)]',
          'bg-[color-mix(in_srgb,var(--ae-surface)_72%,transparent)]',
          'text-[var(--ae-foreground-muted)]',
        )}
      >
        <SearchOffIcon />
      </span>

      <h3 className='mt-4 text-sm font-semibold text-[var(--ae-foreground)]'>
        No results for “{query}”
      </h3>

      <p className='mt-1 max-w-sm text-sm leading-6 text-[var(--ae-foreground-muted)]'>
        {message}
      </p>
    </div>
  )
}

interface SearchHintProps {
  keys: readonly string[]
  label: string
}

function SearchHint({ keys, label }: Readonly<SearchHintProps>) {
  return (
    <span className='inline-flex items-center gap-1.5'>
      <span className='inline-flex items-center gap-1'>
        {keys.map((key) => (
          <kbd
            key={key}
            className={cn(
              'inline-flex min-h-5 min-w-5 items-center justify-center',
              'rounded border border-[var(--ae-border)] px-1',
              'bg-[var(--ae-surface)] font-mono text-[0.625rem]',
              'text-[var(--ae-foreground-muted)]',
              'shadow-[inset_0_-1px_0_rgba(0,0,0,0.16)]',
            )}
          >
            {key}
          </kbd>
        ))}
      </span>

      <span>{label}</span>
    </span>
  )
}

function ShortcutKeys({ compact }: Readonly<{ compact: boolean }>) {
  return (
    <kbd
      className={cn(
        'hidden shrink-0 items-center gap-1 rounded-md border',
        'border-[var(--ae-border)]',
        'bg-[var(--ae-background)] px-1.5 py-1',
        'font-mono text-[0.625rem] font-medium',
        'text-[var(--ae-foreground-muted)]',
        'shadow-[inset_0_-1px_0_rgba(0,0,0,0.14)] sm:inline-flex',
        compact && 'sm:hidden',
      )}
    >
      <span>Ctrl</span>
      <span>K</span>
    </kbd>
  )
}

function getSearchScopeLabel(audience: DocsAudience | undefined): string {
  if (audience === 'developer') {
    return 'Searching developer documentation'
  }

  if (audience === 'user') {
    return 'Searching user documentation'
  }

  return 'Searching all documentation'
}

function getResultsStatus(query: string, resultCount: number): string {
  if (query.trim().length === 0) {
    return 'Enter a search term'
  }

  if (resultCount === 0) {
    return 'No results'
  }

  return `${resultCount} ${resultCount === 1 ? 'result' : 'results'}`
}

function isEditableTarget(target: EventTarget | null): boolean {
  if (!(target instanceof HTMLElement)) return false

  return (
    target.isContentEditable ||
    target instanceof HTMLInputElement ||
    target instanceof HTMLTextAreaElement ||
    target instanceof HTMLSelectElement
  )
}

function SearchIcon({ className }: Readonly<{ className?: string }>) {
  return (
    <svg
      aria-hidden='true'
      className={className}
      fill='none'
      viewBox='0 0 24 24'
    >
      <circle
        cx='11'
        cy='11'
        r='6.5'
        stroke='currentColor'
        strokeWidth='1.75'
      />

      <path
        d='m16 16 4 4'
        stroke='currentColor'
        strokeLinecap='round'
        strokeWidth='1.75'
      />
    </svg>
  )
}

function SearchOffIcon() {
  return (
    <svg aria-hidden='true' className='size-6' fill='none' viewBox='0 0 24 24'>
      <circle
        cx='11'
        cy='11'
        r='6.5'
        stroke='currentColor'
        strokeWidth='1.75'
      />

      <path
        d='m16 16 4 4M7.5 7.5l7 7'
        stroke='currentColor'
        strokeLinecap='round'
        strokeWidth='1.75'
      />
    </svg>
  )
}

function CloseIcon({ className = 'size-5' }: Readonly<{ className?: string }>) {
  return (
    <svg
      aria-hidden='true'
      className={className}
      fill='none'
      viewBox='0 0 24 24'
    >
      <path
        d='m6 6 12 12M18 6 6 18'
        stroke='currentColor'
        strokeLinecap='round'
        strokeWidth='1.75'
      />
    </svg>
  )
}

function ArrowRightIcon({ className }: Readonly<{ className?: string }>) {
  return (
    <svg
      aria-hidden='true'
      className={className}
      fill='none'
      viewBox='0 0 24 24'
    >
      <path
        d='M5 12h14m-5-5 5 5-5 5'
        stroke='currentColor'
        strokeLinecap='round'
        strokeLinejoin='round'
        strokeWidth='1.75'
      />
    </svg>
  )
}

function UserGuideIcon() {
  return (
    <svg aria-hidden='true' className='size-4' fill='none' viewBox='0 0 24 24'>
      <path
        d='M5.5 4.75h8.25A2.25 2.25 0 0 1 16 7v12.25H7.75A2.25 2.25 0 0 1 5.5 17V4.75Z'
        stroke='currentColor'
        strokeLinejoin='round'
        strokeWidth='1.7'
      />

      <path
        d='M16 7h1.25a2.25 2.25 0 0 1 2.25 2.25V19.25H16M8.75 9h4M8.75 12.25h4'
        stroke='currentColor'
        strokeLinecap='round'
        strokeWidth='1.7'
      />
    </svg>
  )
}

function DeveloperIcon() {
  return (
    <svg aria-hidden='true' className='size-4' fill='none' viewBox='0 0 24 24'>
      <path
        d='m8.5 7-5 5 5 5M15.5 7l5 5-5 5M13.5 4.5l-3 15'
        stroke='currentColor'
        strokeLinecap='round'
        strokeLinejoin='round'
        strokeWidth='1.7'
      />
    </svg>
  )
}

export default DocsSearch
