import { z } from 'zod';
/**
 * Internal user session entity ID.
 */
export declare const UserSessionIdSchema: z.ZodUUID;
/**
 * Internal user ID.
 */
export declare const UserSessionUserIdSchema: z.ZodUUID;
/**
 * Hashed session token.
 *
 * Never store or expose a raw session token.
 */
export declare const UserSessionTokenHashSchema: z.ZodString;
/**
 * User-provided or detected device name.
 */
export declare const UserSessionDeviceNameSchema: z.ZodString;
/**
 * Browser or client user agent.
 */
export declare const UserSessionUserAgentSchema: z.ZodString;
/**
 * IPv4 or IPv6 address.
 *
 * Kept simple because exact IP validation can get annoying fast.
 */
export declare const UserSessionIpAddressSchema: z.ZodString;
/**
 * Full internal GeoIP data.
 *
 * Latitude and longitude are internal only.
 */
export declare const UserSessionGeoIpSchema: z.ZodObject<
  {
    country: z.ZodOptional<
      z.ZodEnum<{
        readonly Afghanistan: 'AF';
        readonly AlandIslands: 'AX';
        readonly Albania: 'AL';
        readonly Algeria: 'DZ';
        readonly AmericanSamoa: 'AS';
        readonly Andorra: 'AD';
        readonly Angola: 'AO';
        readonly Anguilla: 'AI';
        readonly Antarctica: 'AQ';
        readonly AntiguaAndBarbuda: 'AG';
        readonly Argentina: 'AR';
        readonly Armenia: 'AM';
        readonly Aruba: 'AW';
        readonly Australia: 'AU';
        readonly Austria: 'AT';
        readonly Azerbaijan: 'AZ';
        readonly Bahamas: 'BS';
        readonly Bahrain: 'BH';
        readonly Bangladesh: 'BD';
        readonly Barbados: 'BB';
        readonly Belarus: 'BY';
        readonly Belgium: 'BE';
        readonly Belize: 'BZ';
        readonly Benin: 'BJ';
        readonly Bermuda: 'BM';
        readonly Bhutan: 'BT';
        readonly Bolivia: 'BO';
        readonly BonaireSintEustatiusAndSaba: 'BQ';
        readonly BosniaAndHerzegovina: 'BA';
        readonly Botswana: 'BW';
        readonly BouvetIsland: 'BV';
        readonly Brazil: 'BR';
        readonly BritishIndianOceanTerritory: 'IO';
        readonly BruneiDarussalam: 'BN';
        readonly Bulgaria: 'BG';
        readonly BurkinaFaso: 'BF';
        readonly Burundi: 'BI';
        readonly CaboVerde: 'CV';
        readonly Cambodia: 'KH';
        readonly Cameroon: 'CM';
        readonly Canada: 'CA';
        readonly CaymanIslands: 'KY';
        readonly CentralAfricanRepublic: 'CF';
        readonly Chad: 'TD';
        readonly Chile: 'CL';
        readonly China: 'CN';
        readonly ChristmasIsland: 'CX';
        readonly CocosKeelingIslands: 'CC';
        readonly Colombia: 'CO';
        readonly Comoros: 'KM';
        readonly Congo: 'CG';
        readonly CongoDemocraticRepublicOfThe: 'CD';
        readonly CookIslands: 'CK';
        readonly CostaRica: 'CR';
        readonly CoteDIvoire: 'CI';
        readonly Croatia: 'HR';
        readonly Cuba: 'CU';
        readonly Curacao: 'CW';
        readonly Cyprus: 'CY';
        readonly Czechia: 'CZ';
        readonly Denmark: 'DK';
        readonly Djibouti: 'DJ';
        readonly Dominica: 'DM';
        readonly DominicanRepublic: 'DO';
        readonly Ecuador: 'EC';
        readonly Egypt: 'EG';
        readonly ElSalvador: 'SV';
        readonly EquatorialGuinea: 'GQ';
        readonly Eritrea: 'ER';
        readonly Estonia: 'EE';
        readonly Eswatini: 'SZ';
        readonly Ethiopia: 'ET';
        readonly FalklandIslands: 'FK';
        readonly FaroeIslands: 'FO';
        readonly Fiji: 'FJ';
        readonly Finland: 'FI';
        readonly France: 'FR';
        readonly FrenchGuiana: 'GF';
        readonly FrenchPolynesia: 'PF';
        readonly FrenchSouthernTerritories: 'TF';
        readonly Gabon: 'GA';
        readonly Gambia: 'GM';
        readonly Georgia: 'GE';
        readonly Germany: 'DE';
        readonly Ghana: 'GH';
        readonly Gibraltar: 'GI';
        readonly Greece: 'GR';
        readonly Greenland: 'GL';
        readonly Grenada: 'GD';
        readonly Guadeloupe: 'GP';
        readonly Guam: 'GU';
        readonly Guatemala: 'GT';
        readonly Guernsey: 'GG';
        readonly Guinea: 'GN';
        readonly GuineaBissau: 'GW';
        readonly Guyana: 'GY';
        readonly Haiti: 'HT';
        readonly HeardIslandAndMcDonaldIslands: 'HM';
        readonly HolySee: 'VA';
        readonly Honduras: 'HN';
        readonly HongKong: 'HK';
        readonly Hungary: 'HU';
        readonly Iceland: 'IS';
        readonly India: 'IN';
        readonly Indonesia: 'ID';
        readonly Iran: 'IR';
        readonly Iraq: 'IQ';
        readonly Ireland: 'IE';
        readonly IsleOfMan: 'IM';
        readonly Israel: 'IL';
        readonly Italy: 'IT';
        readonly Jamaica: 'JM';
        readonly Japan: 'JP';
        readonly Jersey: 'JE';
        readonly Jordan: 'JO';
        readonly Kazakhstan: 'KZ';
        readonly Kenya: 'KE';
        readonly Kiribati: 'KI';
        readonly KoreaDemocraticPeoplesRepublicOf: 'KP';
        readonly KoreaRepublicOf: 'KR';
        readonly Kuwait: 'KW';
        readonly Kyrgyzstan: 'KG';
        readonly LaoPeoplesDemocraticRepublic: 'LA';
        readonly Latvia: 'LV';
        readonly Lebanon: 'LB';
        readonly Lesotho: 'LS';
        readonly Liberia: 'LR';
        readonly Libya: 'LY';
        readonly Liechtenstein: 'LI';
        readonly Lithuania: 'LT';
        readonly Luxembourg: 'LU';
        readonly Macao: 'MO';
        readonly Madagascar: 'MG';
        readonly Malawi: 'MW';
        readonly Malaysia: 'MY';
        readonly Maldives: 'MV';
        readonly Mali: 'ML';
        readonly Malta: 'MT';
        readonly MarshallIslands: 'MH';
        readonly Martinique: 'MQ';
        readonly Mauritania: 'MR';
        readonly Mauritius: 'MU';
        readonly Mayotte: 'YT';
        readonly Mexico: 'MX';
        readonly Micronesia: 'FM';
        readonly Moldova: 'MD';
        readonly Monaco: 'MC';
        readonly Mongolia: 'MN';
        readonly Montenegro: 'ME';
        readonly Montserrat: 'MS';
        readonly Morocco: 'MA';
        readonly Mozambique: 'MZ';
        readonly Myanmar: 'MM';
        readonly Namibia: 'NA';
        readonly Nauru: 'NR';
        readonly Nepal: 'NP';
        readonly Netherlands: 'NL';
        readonly NewCaledonia: 'NC';
        readonly NewZealand: 'NZ';
        readonly Nicaragua: 'NI';
        readonly Niger: 'NE';
        readonly Nigeria: 'NG';
        readonly Niue: 'NU';
        readonly NorfolkIsland: 'NF';
        readonly NorthMacedonia: 'MK';
        readonly NorthernMarianaIslands: 'MP';
        readonly Norway: 'NO';
        readonly Oman: 'OM';
        readonly Pakistan: 'PK';
        readonly Palau: 'PW';
        readonly Palestine: 'PS';
        readonly Panama: 'PA';
        readonly PapuaNewGuinea: 'PG';
        readonly Paraguay: 'PY';
        readonly Peru: 'PE';
        readonly Philippines: 'PH';
        readonly Pitcairn: 'PN';
        readonly Poland: 'PL';
        readonly Portugal: 'PT';
        readonly PuertoRico: 'PR';
        readonly Qatar: 'QA';
        readonly Reunion: 'RE';
        readonly Romania: 'RO';
        readonly RussianFederation: 'RU';
        readonly Rwanda: 'RW';
        readonly SaintBarthelemy: 'BL';
        readonly SaintHelenaAscensionAndTristanDaCunha: 'SH';
        readonly SaintKittsAndNevis: 'KN';
        readonly SaintLucia: 'LC';
        readonly SaintMartin: 'MF';
        readonly SaintPierreAndMiquelon: 'PM';
        readonly SaintVincentAndTheGrenadines: 'VC';
        readonly Samoa: 'WS';
        readonly SanMarino: 'SM';
        readonly SaoTomeAndPrincipe: 'ST';
        readonly SaudiArabia: 'SA';
        readonly Senegal: 'SN';
        readonly Serbia: 'RS';
        readonly Seychelles: 'SC';
        readonly SierraLeone: 'SL';
        readonly Singapore: 'SG';
        readonly SintMaarten: 'SX';
        readonly Slovakia: 'SK';
        readonly Slovenia: 'SI';
        readonly SolomonIslands: 'SB';
        readonly Somalia: 'SO';
        readonly SouthAfrica: 'ZA';
        readonly SouthGeorgiaAndTheSouthSandwichIslands: 'GS';
        readonly SouthSudan: 'SS';
        readonly Spain: 'ES';
        readonly SriLanka: 'LK';
        readonly Sudan: 'SD';
        readonly Suriname: 'SR';
        readonly SvalbardAndJanMayen: 'SJ';
        readonly Sweden: 'SE';
        readonly Switzerland: 'CH';
        readonly SyrianArabRepublic: 'SY';
        readonly Taiwan: 'TW';
        readonly Tajikistan: 'TJ';
        readonly Tanzania: 'TZ';
        readonly Thailand: 'TH';
        readonly TimorLeste: 'TL';
        readonly Togo: 'TG';
        readonly Tokelau: 'TK';
        readonly Tonga: 'TO';
        readonly TrinidadAndTobago: 'TT';
        readonly Tunisia: 'TN';
        readonly Turkiye: 'TR';
        readonly Turkmenistan: 'TM';
        readonly TurksAndCaicosIslands: 'TC';
        readonly Tuvalu: 'TV';
        readonly Uganda: 'UG';
        readonly Ukraine: 'UA';
        readonly UnitedArabEmirates: 'AE';
        readonly UnitedKingdom: 'GB';
        readonly UnitedStates: 'US';
        readonly UnitedStatesMinorOutlyingIslands: 'UM';
        readonly Uruguay: 'UY';
        readonly Uzbekistan: 'UZ';
        readonly Vanuatu: 'VU';
        readonly Venezuela: 'VE';
        readonly VietNam: 'VN';
        readonly VirginIslandsBritish: 'VG';
        readonly VirginIslandsUS: 'VI';
        readonly WallisAndFutuna: 'WF';
        readonly WesternSahara: 'EH';
        readonly Yemen: 'YE';
        readonly Zambia: 'ZM';
        readonly Zimbabwe: 'ZW';
      }>
    >;
    region: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    timezone: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
  },
  z.core.$strip
>;
/**
 * Safe GeoIP data for API responses.
 *
 * Does not include latitude or longitude.
 */
export declare const PublicUserSessionGeoIpSchema: z.ZodObject<
  {
    timezone: z.ZodOptional<z.ZodString>;
    country: z.ZodOptional<
      z.ZodEnum<{
        readonly Afghanistan: 'AF';
        readonly AlandIslands: 'AX';
        readonly Albania: 'AL';
        readonly Algeria: 'DZ';
        readonly AmericanSamoa: 'AS';
        readonly Andorra: 'AD';
        readonly Angola: 'AO';
        readonly Anguilla: 'AI';
        readonly Antarctica: 'AQ';
        readonly AntiguaAndBarbuda: 'AG';
        readonly Argentina: 'AR';
        readonly Armenia: 'AM';
        readonly Aruba: 'AW';
        readonly Australia: 'AU';
        readonly Austria: 'AT';
        readonly Azerbaijan: 'AZ';
        readonly Bahamas: 'BS';
        readonly Bahrain: 'BH';
        readonly Bangladesh: 'BD';
        readonly Barbados: 'BB';
        readonly Belarus: 'BY';
        readonly Belgium: 'BE';
        readonly Belize: 'BZ';
        readonly Benin: 'BJ';
        readonly Bermuda: 'BM';
        readonly Bhutan: 'BT';
        readonly Bolivia: 'BO';
        readonly BonaireSintEustatiusAndSaba: 'BQ';
        readonly BosniaAndHerzegovina: 'BA';
        readonly Botswana: 'BW';
        readonly BouvetIsland: 'BV';
        readonly Brazil: 'BR';
        readonly BritishIndianOceanTerritory: 'IO';
        readonly BruneiDarussalam: 'BN';
        readonly Bulgaria: 'BG';
        readonly BurkinaFaso: 'BF';
        readonly Burundi: 'BI';
        readonly CaboVerde: 'CV';
        readonly Cambodia: 'KH';
        readonly Cameroon: 'CM';
        readonly Canada: 'CA';
        readonly CaymanIslands: 'KY';
        readonly CentralAfricanRepublic: 'CF';
        readonly Chad: 'TD';
        readonly Chile: 'CL';
        readonly China: 'CN';
        readonly ChristmasIsland: 'CX';
        readonly CocosKeelingIslands: 'CC';
        readonly Colombia: 'CO';
        readonly Comoros: 'KM';
        readonly Congo: 'CG';
        readonly CongoDemocraticRepublicOfThe: 'CD';
        readonly CookIslands: 'CK';
        readonly CostaRica: 'CR';
        readonly CoteDIvoire: 'CI';
        readonly Croatia: 'HR';
        readonly Cuba: 'CU';
        readonly Curacao: 'CW';
        readonly Cyprus: 'CY';
        readonly Czechia: 'CZ';
        readonly Denmark: 'DK';
        readonly Djibouti: 'DJ';
        readonly Dominica: 'DM';
        readonly DominicanRepublic: 'DO';
        readonly Ecuador: 'EC';
        readonly Egypt: 'EG';
        readonly ElSalvador: 'SV';
        readonly EquatorialGuinea: 'GQ';
        readonly Eritrea: 'ER';
        readonly Estonia: 'EE';
        readonly Eswatini: 'SZ';
        readonly Ethiopia: 'ET';
        readonly FalklandIslands: 'FK';
        readonly FaroeIslands: 'FO';
        readonly Fiji: 'FJ';
        readonly Finland: 'FI';
        readonly France: 'FR';
        readonly FrenchGuiana: 'GF';
        readonly FrenchPolynesia: 'PF';
        readonly FrenchSouthernTerritories: 'TF';
        readonly Gabon: 'GA';
        readonly Gambia: 'GM';
        readonly Georgia: 'GE';
        readonly Germany: 'DE';
        readonly Ghana: 'GH';
        readonly Gibraltar: 'GI';
        readonly Greece: 'GR';
        readonly Greenland: 'GL';
        readonly Grenada: 'GD';
        readonly Guadeloupe: 'GP';
        readonly Guam: 'GU';
        readonly Guatemala: 'GT';
        readonly Guernsey: 'GG';
        readonly Guinea: 'GN';
        readonly GuineaBissau: 'GW';
        readonly Guyana: 'GY';
        readonly Haiti: 'HT';
        readonly HeardIslandAndMcDonaldIslands: 'HM';
        readonly HolySee: 'VA';
        readonly Honduras: 'HN';
        readonly HongKong: 'HK';
        readonly Hungary: 'HU';
        readonly Iceland: 'IS';
        readonly India: 'IN';
        readonly Indonesia: 'ID';
        readonly Iran: 'IR';
        readonly Iraq: 'IQ';
        readonly Ireland: 'IE';
        readonly IsleOfMan: 'IM';
        readonly Israel: 'IL';
        readonly Italy: 'IT';
        readonly Jamaica: 'JM';
        readonly Japan: 'JP';
        readonly Jersey: 'JE';
        readonly Jordan: 'JO';
        readonly Kazakhstan: 'KZ';
        readonly Kenya: 'KE';
        readonly Kiribati: 'KI';
        readonly KoreaDemocraticPeoplesRepublicOf: 'KP';
        readonly KoreaRepublicOf: 'KR';
        readonly Kuwait: 'KW';
        readonly Kyrgyzstan: 'KG';
        readonly LaoPeoplesDemocraticRepublic: 'LA';
        readonly Latvia: 'LV';
        readonly Lebanon: 'LB';
        readonly Lesotho: 'LS';
        readonly Liberia: 'LR';
        readonly Libya: 'LY';
        readonly Liechtenstein: 'LI';
        readonly Lithuania: 'LT';
        readonly Luxembourg: 'LU';
        readonly Macao: 'MO';
        readonly Madagascar: 'MG';
        readonly Malawi: 'MW';
        readonly Malaysia: 'MY';
        readonly Maldives: 'MV';
        readonly Mali: 'ML';
        readonly Malta: 'MT';
        readonly MarshallIslands: 'MH';
        readonly Martinique: 'MQ';
        readonly Mauritania: 'MR';
        readonly Mauritius: 'MU';
        readonly Mayotte: 'YT';
        readonly Mexico: 'MX';
        readonly Micronesia: 'FM';
        readonly Moldova: 'MD';
        readonly Monaco: 'MC';
        readonly Mongolia: 'MN';
        readonly Montenegro: 'ME';
        readonly Montserrat: 'MS';
        readonly Morocco: 'MA';
        readonly Mozambique: 'MZ';
        readonly Myanmar: 'MM';
        readonly Namibia: 'NA';
        readonly Nauru: 'NR';
        readonly Nepal: 'NP';
        readonly Netherlands: 'NL';
        readonly NewCaledonia: 'NC';
        readonly NewZealand: 'NZ';
        readonly Nicaragua: 'NI';
        readonly Niger: 'NE';
        readonly Nigeria: 'NG';
        readonly Niue: 'NU';
        readonly NorfolkIsland: 'NF';
        readonly NorthMacedonia: 'MK';
        readonly NorthernMarianaIslands: 'MP';
        readonly Norway: 'NO';
        readonly Oman: 'OM';
        readonly Pakistan: 'PK';
        readonly Palau: 'PW';
        readonly Palestine: 'PS';
        readonly Panama: 'PA';
        readonly PapuaNewGuinea: 'PG';
        readonly Paraguay: 'PY';
        readonly Peru: 'PE';
        readonly Philippines: 'PH';
        readonly Pitcairn: 'PN';
        readonly Poland: 'PL';
        readonly Portugal: 'PT';
        readonly PuertoRico: 'PR';
        readonly Qatar: 'QA';
        readonly Reunion: 'RE';
        readonly Romania: 'RO';
        readonly RussianFederation: 'RU';
        readonly Rwanda: 'RW';
        readonly SaintBarthelemy: 'BL';
        readonly SaintHelenaAscensionAndTristanDaCunha: 'SH';
        readonly SaintKittsAndNevis: 'KN';
        readonly SaintLucia: 'LC';
        readonly SaintMartin: 'MF';
        readonly SaintPierreAndMiquelon: 'PM';
        readonly SaintVincentAndTheGrenadines: 'VC';
        readonly Samoa: 'WS';
        readonly SanMarino: 'SM';
        readonly SaoTomeAndPrincipe: 'ST';
        readonly SaudiArabia: 'SA';
        readonly Senegal: 'SN';
        readonly Serbia: 'RS';
        readonly Seychelles: 'SC';
        readonly SierraLeone: 'SL';
        readonly Singapore: 'SG';
        readonly SintMaarten: 'SX';
        readonly Slovakia: 'SK';
        readonly Slovenia: 'SI';
        readonly SolomonIslands: 'SB';
        readonly Somalia: 'SO';
        readonly SouthAfrica: 'ZA';
        readonly SouthGeorgiaAndTheSouthSandwichIslands: 'GS';
        readonly SouthSudan: 'SS';
        readonly Spain: 'ES';
        readonly SriLanka: 'LK';
        readonly Sudan: 'SD';
        readonly Suriname: 'SR';
        readonly SvalbardAndJanMayen: 'SJ';
        readonly Sweden: 'SE';
        readonly Switzerland: 'CH';
        readonly SyrianArabRepublic: 'SY';
        readonly Taiwan: 'TW';
        readonly Tajikistan: 'TJ';
        readonly Tanzania: 'TZ';
        readonly Thailand: 'TH';
        readonly TimorLeste: 'TL';
        readonly Togo: 'TG';
        readonly Tokelau: 'TK';
        readonly Tonga: 'TO';
        readonly TrinidadAndTobago: 'TT';
        readonly Tunisia: 'TN';
        readonly Turkiye: 'TR';
        readonly Turkmenistan: 'TM';
        readonly TurksAndCaicosIslands: 'TC';
        readonly Tuvalu: 'TV';
        readonly Uganda: 'UG';
        readonly Ukraine: 'UA';
        readonly UnitedArabEmirates: 'AE';
        readonly UnitedKingdom: 'GB';
        readonly UnitedStates: 'US';
        readonly UnitedStatesMinorOutlyingIslands: 'UM';
        readonly Uruguay: 'UY';
        readonly Uzbekistan: 'UZ';
        readonly Vanuatu: 'VU';
        readonly Venezuela: 'VE';
        readonly VietNam: 'VN';
        readonly VirginIslandsBritish: 'VG';
        readonly VirginIslandsUS: 'VI';
        readonly WallisAndFutuna: 'WF';
        readonly WesternSahara: 'EH';
        readonly Yemen: 'YE';
        readonly Zambia: 'ZM';
        readonly Zimbabwe: 'ZW';
      }>
    >;
    region: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
  },
  z.core.$strip
>;
/**
 * Full internal user session entity schema.
 *
 * Includes `tokenHash`, so do not use this schema for API responses.
 */
export declare const UserSessionEntitySchema: z.ZodObject<
  {
    id: z.ZodUUID;
    userId: z.ZodUUID;
    tokenHash: z.ZodString;
    deviceName: z.ZodNullable<z.ZodString>;
    userAgent: z.ZodNullable<z.ZodString>;
    ipAddress: z.ZodNullable<z.ZodString>;
    geoIp: z.ZodNullable<
      z.ZodObject<
        {
          country: z.ZodOptional<
            z.ZodEnum<{
              readonly Afghanistan: 'AF';
              readonly AlandIslands: 'AX';
              readonly Albania: 'AL';
              readonly Algeria: 'DZ';
              readonly AmericanSamoa: 'AS';
              readonly Andorra: 'AD';
              readonly Angola: 'AO';
              readonly Anguilla: 'AI';
              readonly Antarctica: 'AQ';
              readonly AntiguaAndBarbuda: 'AG';
              readonly Argentina: 'AR';
              readonly Armenia: 'AM';
              readonly Aruba: 'AW';
              readonly Australia: 'AU';
              readonly Austria: 'AT';
              readonly Azerbaijan: 'AZ';
              readonly Bahamas: 'BS';
              readonly Bahrain: 'BH';
              readonly Bangladesh: 'BD';
              readonly Barbados: 'BB';
              readonly Belarus: 'BY';
              readonly Belgium: 'BE';
              readonly Belize: 'BZ';
              readonly Benin: 'BJ';
              readonly Bermuda: 'BM';
              readonly Bhutan: 'BT';
              readonly Bolivia: 'BO';
              readonly BonaireSintEustatiusAndSaba: 'BQ';
              readonly BosniaAndHerzegovina: 'BA';
              readonly Botswana: 'BW';
              readonly BouvetIsland: 'BV';
              readonly Brazil: 'BR';
              readonly BritishIndianOceanTerritory: 'IO';
              readonly BruneiDarussalam: 'BN';
              readonly Bulgaria: 'BG';
              readonly BurkinaFaso: 'BF';
              readonly Burundi: 'BI';
              readonly CaboVerde: 'CV';
              readonly Cambodia: 'KH';
              readonly Cameroon: 'CM';
              readonly Canada: 'CA';
              readonly CaymanIslands: 'KY';
              readonly CentralAfricanRepublic: 'CF';
              readonly Chad: 'TD';
              readonly Chile: 'CL';
              readonly China: 'CN';
              readonly ChristmasIsland: 'CX';
              readonly CocosKeelingIslands: 'CC';
              readonly Colombia: 'CO';
              readonly Comoros: 'KM';
              readonly Congo: 'CG';
              readonly CongoDemocraticRepublicOfThe: 'CD';
              readonly CookIslands: 'CK';
              readonly CostaRica: 'CR';
              readonly CoteDIvoire: 'CI';
              readonly Croatia: 'HR';
              readonly Cuba: 'CU';
              readonly Curacao: 'CW';
              readonly Cyprus: 'CY';
              readonly Czechia: 'CZ';
              readonly Denmark: 'DK';
              readonly Djibouti: 'DJ';
              readonly Dominica: 'DM';
              readonly DominicanRepublic: 'DO';
              readonly Ecuador: 'EC';
              readonly Egypt: 'EG';
              readonly ElSalvador: 'SV';
              readonly EquatorialGuinea: 'GQ';
              readonly Eritrea: 'ER';
              readonly Estonia: 'EE';
              readonly Eswatini: 'SZ';
              readonly Ethiopia: 'ET';
              readonly FalklandIslands: 'FK';
              readonly FaroeIslands: 'FO';
              readonly Fiji: 'FJ';
              readonly Finland: 'FI';
              readonly France: 'FR';
              readonly FrenchGuiana: 'GF';
              readonly FrenchPolynesia: 'PF';
              readonly FrenchSouthernTerritories: 'TF';
              readonly Gabon: 'GA';
              readonly Gambia: 'GM';
              readonly Georgia: 'GE';
              readonly Germany: 'DE';
              readonly Ghana: 'GH';
              readonly Gibraltar: 'GI';
              readonly Greece: 'GR';
              readonly Greenland: 'GL';
              readonly Grenada: 'GD';
              readonly Guadeloupe: 'GP';
              readonly Guam: 'GU';
              readonly Guatemala: 'GT';
              readonly Guernsey: 'GG';
              readonly Guinea: 'GN';
              readonly GuineaBissau: 'GW';
              readonly Guyana: 'GY';
              readonly Haiti: 'HT';
              readonly HeardIslandAndMcDonaldIslands: 'HM';
              readonly HolySee: 'VA';
              readonly Honduras: 'HN';
              readonly HongKong: 'HK';
              readonly Hungary: 'HU';
              readonly Iceland: 'IS';
              readonly India: 'IN';
              readonly Indonesia: 'ID';
              readonly Iran: 'IR';
              readonly Iraq: 'IQ';
              readonly Ireland: 'IE';
              readonly IsleOfMan: 'IM';
              readonly Israel: 'IL';
              readonly Italy: 'IT';
              readonly Jamaica: 'JM';
              readonly Japan: 'JP';
              readonly Jersey: 'JE';
              readonly Jordan: 'JO';
              readonly Kazakhstan: 'KZ';
              readonly Kenya: 'KE';
              readonly Kiribati: 'KI';
              readonly KoreaDemocraticPeoplesRepublicOf: 'KP';
              readonly KoreaRepublicOf: 'KR';
              readonly Kuwait: 'KW';
              readonly Kyrgyzstan: 'KG';
              readonly LaoPeoplesDemocraticRepublic: 'LA';
              readonly Latvia: 'LV';
              readonly Lebanon: 'LB';
              readonly Lesotho: 'LS';
              readonly Liberia: 'LR';
              readonly Libya: 'LY';
              readonly Liechtenstein: 'LI';
              readonly Lithuania: 'LT';
              readonly Luxembourg: 'LU';
              readonly Macao: 'MO';
              readonly Madagascar: 'MG';
              readonly Malawi: 'MW';
              readonly Malaysia: 'MY';
              readonly Maldives: 'MV';
              readonly Mali: 'ML';
              readonly Malta: 'MT';
              readonly MarshallIslands: 'MH';
              readonly Martinique: 'MQ';
              readonly Mauritania: 'MR';
              readonly Mauritius: 'MU';
              readonly Mayotte: 'YT';
              readonly Mexico: 'MX';
              readonly Micronesia: 'FM';
              readonly Moldova: 'MD';
              readonly Monaco: 'MC';
              readonly Mongolia: 'MN';
              readonly Montenegro: 'ME';
              readonly Montserrat: 'MS';
              readonly Morocco: 'MA';
              readonly Mozambique: 'MZ';
              readonly Myanmar: 'MM';
              readonly Namibia: 'NA';
              readonly Nauru: 'NR';
              readonly Nepal: 'NP';
              readonly Netherlands: 'NL';
              readonly NewCaledonia: 'NC';
              readonly NewZealand: 'NZ';
              readonly Nicaragua: 'NI';
              readonly Niger: 'NE';
              readonly Nigeria: 'NG';
              readonly Niue: 'NU';
              readonly NorfolkIsland: 'NF';
              readonly NorthMacedonia: 'MK';
              readonly NorthernMarianaIslands: 'MP';
              readonly Norway: 'NO';
              readonly Oman: 'OM';
              readonly Pakistan: 'PK';
              readonly Palau: 'PW';
              readonly Palestine: 'PS';
              readonly Panama: 'PA';
              readonly PapuaNewGuinea: 'PG';
              readonly Paraguay: 'PY';
              readonly Peru: 'PE';
              readonly Philippines: 'PH';
              readonly Pitcairn: 'PN';
              readonly Poland: 'PL';
              readonly Portugal: 'PT';
              readonly PuertoRico: 'PR';
              readonly Qatar: 'QA';
              readonly Reunion: 'RE';
              readonly Romania: 'RO';
              readonly RussianFederation: 'RU';
              readonly Rwanda: 'RW';
              readonly SaintBarthelemy: 'BL';
              readonly SaintHelenaAscensionAndTristanDaCunha: 'SH';
              readonly SaintKittsAndNevis: 'KN';
              readonly SaintLucia: 'LC';
              readonly SaintMartin: 'MF';
              readonly SaintPierreAndMiquelon: 'PM';
              readonly SaintVincentAndTheGrenadines: 'VC';
              readonly Samoa: 'WS';
              readonly SanMarino: 'SM';
              readonly SaoTomeAndPrincipe: 'ST';
              readonly SaudiArabia: 'SA';
              readonly Senegal: 'SN';
              readonly Serbia: 'RS';
              readonly Seychelles: 'SC';
              readonly SierraLeone: 'SL';
              readonly Singapore: 'SG';
              readonly SintMaarten: 'SX';
              readonly Slovakia: 'SK';
              readonly Slovenia: 'SI';
              readonly SolomonIslands: 'SB';
              readonly Somalia: 'SO';
              readonly SouthAfrica: 'ZA';
              readonly SouthGeorgiaAndTheSouthSandwichIslands: 'GS';
              readonly SouthSudan: 'SS';
              readonly Spain: 'ES';
              readonly SriLanka: 'LK';
              readonly Sudan: 'SD';
              readonly Suriname: 'SR';
              readonly SvalbardAndJanMayen: 'SJ';
              readonly Sweden: 'SE';
              readonly Switzerland: 'CH';
              readonly SyrianArabRepublic: 'SY';
              readonly Taiwan: 'TW';
              readonly Tajikistan: 'TJ';
              readonly Tanzania: 'TZ';
              readonly Thailand: 'TH';
              readonly TimorLeste: 'TL';
              readonly Togo: 'TG';
              readonly Tokelau: 'TK';
              readonly Tonga: 'TO';
              readonly TrinidadAndTobago: 'TT';
              readonly Tunisia: 'TN';
              readonly Turkiye: 'TR';
              readonly Turkmenistan: 'TM';
              readonly TurksAndCaicosIslands: 'TC';
              readonly Tuvalu: 'TV';
              readonly Uganda: 'UG';
              readonly Ukraine: 'UA';
              readonly UnitedArabEmirates: 'AE';
              readonly UnitedKingdom: 'GB';
              readonly UnitedStates: 'US';
              readonly UnitedStatesMinorOutlyingIslands: 'UM';
              readonly Uruguay: 'UY';
              readonly Uzbekistan: 'UZ';
              readonly Vanuatu: 'VU';
              readonly Venezuela: 'VE';
              readonly VietNam: 'VN';
              readonly VirginIslandsBritish: 'VG';
              readonly VirginIslandsUS: 'VI';
              readonly WallisAndFutuna: 'WF';
              readonly WesternSahara: 'EH';
              readonly Yemen: 'YE';
              readonly Zambia: 'ZM';
              readonly Zimbabwe: 'ZW';
            }>
          >;
          region: z.ZodOptional<z.ZodString>;
          city: z.ZodOptional<z.ZodString>;
          timezone: z.ZodOptional<z.ZodString>;
          latitude: z.ZodOptional<z.ZodNumber>;
          longitude: z.ZodOptional<z.ZodNumber>;
        },
        z.core.$strip
      >
    >;
    lastSeenAt: z.ZodNullable<z.ZodCoercedDate<unknown>>;
    expiresAt: z.ZodCoercedDate<unknown>;
    revokedAt: z.ZodNullable<z.ZodCoercedDate<unknown>>;
    createdAt: z.ZodCoercedDate<unknown>;
    updatedAt: z.ZodCoercedDate<unknown>;
    deletedAt: z.ZodNullable<z.ZodCoercedDate<unknown>>;
  },
  z.core.$strip
>;
/**
 * Data accepted when creating a user session.
 */
export declare const CreateUserSessionEntitySchema: z.ZodObject<
  {
    userId: z.ZodUUID;
    tokenHash: z.ZodString;
    expiresAt: z.ZodCoercedDate<unknown>;
    deviceName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    userAgent: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ipAddress: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    geoIp: z.ZodOptional<
      z.ZodNullable<
        z.ZodObject<
          {
            country: z.ZodOptional<
              z.ZodEnum<{
                readonly Afghanistan: 'AF';
                readonly AlandIslands: 'AX';
                readonly Albania: 'AL';
                readonly Algeria: 'DZ';
                readonly AmericanSamoa: 'AS';
                readonly Andorra: 'AD';
                readonly Angola: 'AO';
                readonly Anguilla: 'AI';
                readonly Antarctica: 'AQ';
                readonly AntiguaAndBarbuda: 'AG';
                readonly Argentina: 'AR';
                readonly Armenia: 'AM';
                readonly Aruba: 'AW';
                readonly Australia: 'AU';
                readonly Austria: 'AT';
                readonly Azerbaijan: 'AZ';
                readonly Bahamas: 'BS';
                readonly Bahrain: 'BH';
                readonly Bangladesh: 'BD';
                readonly Barbados: 'BB';
                readonly Belarus: 'BY';
                readonly Belgium: 'BE';
                readonly Belize: 'BZ';
                readonly Benin: 'BJ';
                readonly Bermuda: 'BM';
                readonly Bhutan: 'BT';
                readonly Bolivia: 'BO';
                readonly BonaireSintEustatiusAndSaba: 'BQ';
                readonly BosniaAndHerzegovina: 'BA';
                readonly Botswana: 'BW';
                readonly BouvetIsland: 'BV';
                readonly Brazil: 'BR';
                readonly BritishIndianOceanTerritory: 'IO';
                readonly BruneiDarussalam: 'BN';
                readonly Bulgaria: 'BG';
                readonly BurkinaFaso: 'BF';
                readonly Burundi: 'BI';
                readonly CaboVerde: 'CV';
                readonly Cambodia: 'KH';
                readonly Cameroon: 'CM';
                readonly Canada: 'CA';
                readonly CaymanIslands: 'KY';
                readonly CentralAfricanRepublic: 'CF';
                readonly Chad: 'TD';
                readonly Chile: 'CL';
                readonly China: 'CN';
                readonly ChristmasIsland: 'CX';
                readonly CocosKeelingIslands: 'CC';
                readonly Colombia: 'CO';
                readonly Comoros: 'KM';
                readonly Congo: 'CG';
                readonly CongoDemocraticRepublicOfThe: 'CD';
                readonly CookIslands: 'CK';
                readonly CostaRica: 'CR';
                readonly CoteDIvoire: 'CI';
                readonly Croatia: 'HR';
                readonly Cuba: 'CU';
                readonly Curacao: 'CW';
                readonly Cyprus: 'CY';
                readonly Czechia: 'CZ';
                readonly Denmark: 'DK';
                readonly Djibouti: 'DJ';
                readonly Dominica: 'DM';
                readonly DominicanRepublic: 'DO';
                readonly Ecuador: 'EC';
                readonly Egypt: 'EG';
                readonly ElSalvador: 'SV';
                readonly EquatorialGuinea: 'GQ';
                readonly Eritrea: 'ER';
                readonly Estonia: 'EE';
                readonly Eswatini: 'SZ';
                readonly Ethiopia: 'ET';
                readonly FalklandIslands: 'FK';
                readonly FaroeIslands: 'FO';
                readonly Fiji: 'FJ';
                readonly Finland: 'FI';
                readonly France: 'FR';
                readonly FrenchGuiana: 'GF';
                readonly FrenchPolynesia: 'PF';
                readonly FrenchSouthernTerritories: 'TF';
                readonly Gabon: 'GA';
                readonly Gambia: 'GM';
                readonly Georgia: 'GE';
                readonly Germany: 'DE';
                readonly Ghana: 'GH';
                readonly Gibraltar: 'GI';
                readonly Greece: 'GR';
                readonly Greenland: 'GL';
                readonly Grenada: 'GD';
                readonly Guadeloupe: 'GP';
                readonly Guam: 'GU';
                readonly Guatemala: 'GT';
                readonly Guernsey: 'GG';
                readonly Guinea: 'GN';
                readonly GuineaBissau: 'GW';
                readonly Guyana: 'GY';
                readonly Haiti: 'HT';
                readonly HeardIslandAndMcDonaldIslands: 'HM';
                readonly HolySee: 'VA';
                readonly Honduras: 'HN';
                readonly HongKong: 'HK';
                readonly Hungary: 'HU';
                readonly Iceland: 'IS';
                readonly India: 'IN';
                readonly Indonesia: 'ID';
                readonly Iran: 'IR';
                readonly Iraq: 'IQ';
                readonly Ireland: 'IE';
                readonly IsleOfMan: 'IM';
                readonly Israel: 'IL';
                readonly Italy: 'IT';
                readonly Jamaica: 'JM';
                readonly Japan: 'JP';
                readonly Jersey: 'JE';
                readonly Jordan: 'JO';
                readonly Kazakhstan: 'KZ';
                readonly Kenya: 'KE';
                readonly Kiribati: 'KI';
                readonly KoreaDemocraticPeoplesRepublicOf: 'KP';
                readonly KoreaRepublicOf: 'KR';
                readonly Kuwait: 'KW';
                readonly Kyrgyzstan: 'KG';
                readonly LaoPeoplesDemocraticRepublic: 'LA';
                readonly Latvia: 'LV';
                readonly Lebanon: 'LB';
                readonly Lesotho: 'LS';
                readonly Liberia: 'LR';
                readonly Libya: 'LY';
                readonly Liechtenstein: 'LI';
                readonly Lithuania: 'LT';
                readonly Luxembourg: 'LU';
                readonly Macao: 'MO';
                readonly Madagascar: 'MG';
                readonly Malawi: 'MW';
                readonly Malaysia: 'MY';
                readonly Maldives: 'MV';
                readonly Mali: 'ML';
                readonly Malta: 'MT';
                readonly MarshallIslands: 'MH';
                readonly Martinique: 'MQ';
                readonly Mauritania: 'MR';
                readonly Mauritius: 'MU';
                readonly Mayotte: 'YT';
                readonly Mexico: 'MX';
                readonly Micronesia: 'FM';
                readonly Moldova: 'MD';
                readonly Monaco: 'MC';
                readonly Mongolia: 'MN';
                readonly Montenegro: 'ME';
                readonly Montserrat: 'MS';
                readonly Morocco: 'MA';
                readonly Mozambique: 'MZ';
                readonly Myanmar: 'MM';
                readonly Namibia: 'NA';
                readonly Nauru: 'NR';
                readonly Nepal: 'NP';
                readonly Netherlands: 'NL';
                readonly NewCaledonia: 'NC';
                readonly NewZealand: 'NZ';
                readonly Nicaragua: 'NI';
                readonly Niger: 'NE';
                readonly Nigeria: 'NG';
                readonly Niue: 'NU';
                readonly NorfolkIsland: 'NF';
                readonly NorthMacedonia: 'MK';
                readonly NorthernMarianaIslands: 'MP';
                readonly Norway: 'NO';
                readonly Oman: 'OM';
                readonly Pakistan: 'PK';
                readonly Palau: 'PW';
                readonly Palestine: 'PS';
                readonly Panama: 'PA';
                readonly PapuaNewGuinea: 'PG';
                readonly Paraguay: 'PY';
                readonly Peru: 'PE';
                readonly Philippines: 'PH';
                readonly Pitcairn: 'PN';
                readonly Poland: 'PL';
                readonly Portugal: 'PT';
                readonly PuertoRico: 'PR';
                readonly Qatar: 'QA';
                readonly Reunion: 'RE';
                readonly Romania: 'RO';
                readonly RussianFederation: 'RU';
                readonly Rwanda: 'RW';
                readonly SaintBarthelemy: 'BL';
                readonly SaintHelenaAscensionAndTristanDaCunha: 'SH';
                readonly SaintKittsAndNevis: 'KN';
                readonly SaintLucia: 'LC';
                readonly SaintMartin: 'MF';
                readonly SaintPierreAndMiquelon: 'PM';
                readonly SaintVincentAndTheGrenadines: 'VC';
                readonly Samoa: 'WS';
                readonly SanMarino: 'SM';
                readonly SaoTomeAndPrincipe: 'ST';
                readonly SaudiArabia: 'SA';
                readonly Senegal: 'SN';
                readonly Serbia: 'RS';
                readonly Seychelles: 'SC';
                readonly SierraLeone: 'SL';
                readonly Singapore: 'SG';
                readonly SintMaarten: 'SX';
                readonly Slovakia: 'SK';
                readonly Slovenia: 'SI';
                readonly SolomonIslands: 'SB';
                readonly Somalia: 'SO';
                readonly SouthAfrica: 'ZA';
                readonly SouthGeorgiaAndTheSouthSandwichIslands: 'GS';
                readonly SouthSudan: 'SS';
                readonly Spain: 'ES';
                readonly SriLanka: 'LK';
                readonly Sudan: 'SD';
                readonly Suriname: 'SR';
                readonly SvalbardAndJanMayen: 'SJ';
                readonly Sweden: 'SE';
                readonly Switzerland: 'CH';
                readonly SyrianArabRepublic: 'SY';
                readonly Taiwan: 'TW';
                readonly Tajikistan: 'TJ';
                readonly Tanzania: 'TZ';
                readonly Thailand: 'TH';
                readonly TimorLeste: 'TL';
                readonly Togo: 'TG';
                readonly Tokelau: 'TK';
                readonly Tonga: 'TO';
                readonly TrinidadAndTobago: 'TT';
                readonly Tunisia: 'TN';
                readonly Turkiye: 'TR';
                readonly Turkmenistan: 'TM';
                readonly TurksAndCaicosIslands: 'TC';
                readonly Tuvalu: 'TV';
                readonly Uganda: 'UG';
                readonly Ukraine: 'UA';
                readonly UnitedArabEmirates: 'AE';
                readonly UnitedKingdom: 'GB';
                readonly UnitedStates: 'US';
                readonly UnitedStatesMinorOutlyingIslands: 'UM';
                readonly Uruguay: 'UY';
                readonly Uzbekistan: 'UZ';
                readonly Vanuatu: 'VU';
                readonly Venezuela: 'VE';
                readonly VietNam: 'VN';
                readonly VirginIslandsBritish: 'VG';
                readonly VirginIslandsUS: 'VI';
                readonly WallisAndFutuna: 'WF';
                readonly WesternSahara: 'EH';
                readonly Yemen: 'YE';
                readonly Zambia: 'ZM';
                readonly Zimbabwe: 'ZW';
              }>
            >;
            region: z.ZodOptional<z.ZodString>;
            city: z.ZodOptional<z.ZodString>;
            timezone: z.ZodOptional<z.ZodString>;
            latitude: z.ZodOptional<z.ZodNumber>;
            longitude: z.ZodOptional<z.ZodNumber>;
          },
          z.core.$strip
        >
      >
    >;
    lastSeenAt: z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>;
    revokedAt: z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>;
  },
  z.core.$strip
>;
/**
 * Data allowed when updating session activity or revoking a session.
 */
export declare const UpdateUserSessionEntitySchema: z.ZodObject<
  {
    deviceName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    userAgent: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ipAddress: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    geoIp: z.ZodOptional<
      z.ZodNullable<
        z.ZodObject<
          {
            country: z.ZodOptional<
              z.ZodEnum<{
                readonly Afghanistan: 'AF';
                readonly AlandIslands: 'AX';
                readonly Albania: 'AL';
                readonly Algeria: 'DZ';
                readonly AmericanSamoa: 'AS';
                readonly Andorra: 'AD';
                readonly Angola: 'AO';
                readonly Anguilla: 'AI';
                readonly Antarctica: 'AQ';
                readonly AntiguaAndBarbuda: 'AG';
                readonly Argentina: 'AR';
                readonly Armenia: 'AM';
                readonly Aruba: 'AW';
                readonly Australia: 'AU';
                readonly Austria: 'AT';
                readonly Azerbaijan: 'AZ';
                readonly Bahamas: 'BS';
                readonly Bahrain: 'BH';
                readonly Bangladesh: 'BD';
                readonly Barbados: 'BB';
                readonly Belarus: 'BY';
                readonly Belgium: 'BE';
                readonly Belize: 'BZ';
                readonly Benin: 'BJ';
                readonly Bermuda: 'BM';
                readonly Bhutan: 'BT';
                readonly Bolivia: 'BO';
                readonly BonaireSintEustatiusAndSaba: 'BQ';
                readonly BosniaAndHerzegovina: 'BA';
                readonly Botswana: 'BW';
                readonly BouvetIsland: 'BV';
                readonly Brazil: 'BR';
                readonly BritishIndianOceanTerritory: 'IO';
                readonly BruneiDarussalam: 'BN';
                readonly Bulgaria: 'BG';
                readonly BurkinaFaso: 'BF';
                readonly Burundi: 'BI';
                readonly CaboVerde: 'CV';
                readonly Cambodia: 'KH';
                readonly Cameroon: 'CM';
                readonly Canada: 'CA';
                readonly CaymanIslands: 'KY';
                readonly CentralAfricanRepublic: 'CF';
                readonly Chad: 'TD';
                readonly Chile: 'CL';
                readonly China: 'CN';
                readonly ChristmasIsland: 'CX';
                readonly CocosKeelingIslands: 'CC';
                readonly Colombia: 'CO';
                readonly Comoros: 'KM';
                readonly Congo: 'CG';
                readonly CongoDemocraticRepublicOfThe: 'CD';
                readonly CookIslands: 'CK';
                readonly CostaRica: 'CR';
                readonly CoteDIvoire: 'CI';
                readonly Croatia: 'HR';
                readonly Cuba: 'CU';
                readonly Curacao: 'CW';
                readonly Cyprus: 'CY';
                readonly Czechia: 'CZ';
                readonly Denmark: 'DK';
                readonly Djibouti: 'DJ';
                readonly Dominica: 'DM';
                readonly DominicanRepublic: 'DO';
                readonly Ecuador: 'EC';
                readonly Egypt: 'EG';
                readonly ElSalvador: 'SV';
                readonly EquatorialGuinea: 'GQ';
                readonly Eritrea: 'ER';
                readonly Estonia: 'EE';
                readonly Eswatini: 'SZ';
                readonly Ethiopia: 'ET';
                readonly FalklandIslands: 'FK';
                readonly FaroeIslands: 'FO';
                readonly Fiji: 'FJ';
                readonly Finland: 'FI';
                readonly France: 'FR';
                readonly FrenchGuiana: 'GF';
                readonly FrenchPolynesia: 'PF';
                readonly FrenchSouthernTerritories: 'TF';
                readonly Gabon: 'GA';
                readonly Gambia: 'GM';
                readonly Georgia: 'GE';
                readonly Germany: 'DE';
                readonly Ghana: 'GH';
                readonly Gibraltar: 'GI';
                readonly Greece: 'GR';
                readonly Greenland: 'GL';
                readonly Grenada: 'GD';
                readonly Guadeloupe: 'GP';
                readonly Guam: 'GU';
                readonly Guatemala: 'GT';
                readonly Guernsey: 'GG';
                readonly Guinea: 'GN';
                readonly GuineaBissau: 'GW';
                readonly Guyana: 'GY';
                readonly Haiti: 'HT';
                readonly HeardIslandAndMcDonaldIslands: 'HM';
                readonly HolySee: 'VA';
                readonly Honduras: 'HN';
                readonly HongKong: 'HK';
                readonly Hungary: 'HU';
                readonly Iceland: 'IS';
                readonly India: 'IN';
                readonly Indonesia: 'ID';
                readonly Iran: 'IR';
                readonly Iraq: 'IQ';
                readonly Ireland: 'IE';
                readonly IsleOfMan: 'IM';
                readonly Israel: 'IL';
                readonly Italy: 'IT';
                readonly Jamaica: 'JM';
                readonly Japan: 'JP';
                readonly Jersey: 'JE';
                readonly Jordan: 'JO';
                readonly Kazakhstan: 'KZ';
                readonly Kenya: 'KE';
                readonly Kiribati: 'KI';
                readonly KoreaDemocraticPeoplesRepublicOf: 'KP';
                readonly KoreaRepublicOf: 'KR';
                readonly Kuwait: 'KW';
                readonly Kyrgyzstan: 'KG';
                readonly LaoPeoplesDemocraticRepublic: 'LA';
                readonly Latvia: 'LV';
                readonly Lebanon: 'LB';
                readonly Lesotho: 'LS';
                readonly Liberia: 'LR';
                readonly Libya: 'LY';
                readonly Liechtenstein: 'LI';
                readonly Lithuania: 'LT';
                readonly Luxembourg: 'LU';
                readonly Macao: 'MO';
                readonly Madagascar: 'MG';
                readonly Malawi: 'MW';
                readonly Malaysia: 'MY';
                readonly Maldives: 'MV';
                readonly Mali: 'ML';
                readonly Malta: 'MT';
                readonly MarshallIslands: 'MH';
                readonly Martinique: 'MQ';
                readonly Mauritania: 'MR';
                readonly Mauritius: 'MU';
                readonly Mayotte: 'YT';
                readonly Mexico: 'MX';
                readonly Micronesia: 'FM';
                readonly Moldova: 'MD';
                readonly Monaco: 'MC';
                readonly Mongolia: 'MN';
                readonly Montenegro: 'ME';
                readonly Montserrat: 'MS';
                readonly Morocco: 'MA';
                readonly Mozambique: 'MZ';
                readonly Myanmar: 'MM';
                readonly Namibia: 'NA';
                readonly Nauru: 'NR';
                readonly Nepal: 'NP';
                readonly Netherlands: 'NL';
                readonly NewCaledonia: 'NC';
                readonly NewZealand: 'NZ';
                readonly Nicaragua: 'NI';
                readonly Niger: 'NE';
                readonly Nigeria: 'NG';
                readonly Niue: 'NU';
                readonly NorfolkIsland: 'NF';
                readonly NorthMacedonia: 'MK';
                readonly NorthernMarianaIslands: 'MP';
                readonly Norway: 'NO';
                readonly Oman: 'OM';
                readonly Pakistan: 'PK';
                readonly Palau: 'PW';
                readonly Palestine: 'PS';
                readonly Panama: 'PA';
                readonly PapuaNewGuinea: 'PG';
                readonly Paraguay: 'PY';
                readonly Peru: 'PE';
                readonly Philippines: 'PH';
                readonly Pitcairn: 'PN';
                readonly Poland: 'PL';
                readonly Portugal: 'PT';
                readonly PuertoRico: 'PR';
                readonly Qatar: 'QA';
                readonly Reunion: 'RE';
                readonly Romania: 'RO';
                readonly RussianFederation: 'RU';
                readonly Rwanda: 'RW';
                readonly SaintBarthelemy: 'BL';
                readonly SaintHelenaAscensionAndTristanDaCunha: 'SH';
                readonly SaintKittsAndNevis: 'KN';
                readonly SaintLucia: 'LC';
                readonly SaintMartin: 'MF';
                readonly SaintPierreAndMiquelon: 'PM';
                readonly SaintVincentAndTheGrenadines: 'VC';
                readonly Samoa: 'WS';
                readonly SanMarino: 'SM';
                readonly SaoTomeAndPrincipe: 'ST';
                readonly SaudiArabia: 'SA';
                readonly Senegal: 'SN';
                readonly Serbia: 'RS';
                readonly Seychelles: 'SC';
                readonly SierraLeone: 'SL';
                readonly Singapore: 'SG';
                readonly SintMaarten: 'SX';
                readonly Slovakia: 'SK';
                readonly Slovenia: 'SI';
                readonly SolomonIslands: 'SB';
                readonly Somalia: 'SO';
                readonly SouthAfrica: 'ZA';
                readonly SouthGeorgiaAndTheSouthSandwichIslands: 'GS';
                readonly SouthSudan: 'SS';
                readonly Spain: 'ES';
                readonly SriLanka: 'LK';
                readonly Sudan: 'SD';
                readonly Suriname: 'SR';
                readonly SvalbardAndJanMayen: 'SJ';
                readonly Sweden: 'SE';
                readonly Switzerland: 'CH';
                readonly SyrianArabRepublic: 'SY';
                readonly Taiwan: 'TW';
                readonly Tajikistan: 'TJ';
                readonly Tanzania: 'TZ';
                readonly Thailand: 'TH';
                readonly TimorLeste: 'TL';
                readonly Togo: 'TG';
                readonly Tokelau: 'TK';
                readonly Tonga: 'TO';
                readonly TrinidadAndTobago: 'TT';
                readonly Tunisia: 'TN';
                readonly Turkiye: 'TR';
                readonly Turkmenistan: 'TM';
                readonly TurksAndCaicosIslands: 'TC';
                readonly Tuvalu: 'TV';
                readonly Uganda: 'UG';
                readonly Ukraine: 'UA';
                readonly UnitedArabEmirates: 'AE';
                readonly UnitedKingdom: 'GB';
                readonly UnitedStates: 'US';
                readonly UnitedStatesMinorOutlyingIslands: 'UM';
                readonly Uruguay: 'UY';
                readonly Uzbekistan: 'UZ';
                readonly Vanuatu: 'VU';
                readonly Venezuela: 'VE';
                readonly VietNam: 'VN';
                readonly VirginIslandsBritish: 'VG';
                readonly VirginIslandsUS: 'VI';
                readonly WallisAndFutuna: 'WF';
                readonly WesternSahara: 'EH';
                readonly Yemen: 'YE';
                readonly Zambia: 'ZM';
                readonly Zimbabwe: 'ZW';
              }>
            >;
            region: z.ZodOptional<z.ZodString>;
            city: z.ZodOptional<z.ZodString>;
            timezone: z.ZodOptional<z.ZodString>;
            latitude: z.ZodOptional<z.ZodNumber>;
            longitude: z.ZodOptional<z.ZodNumber>;
          },
          z.core.$strip
        >
      >
    >;
    lastSeenAt: z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>;
    expiresAt: z.ZodOptional<z.ZodCoercedDate<unknown>>;
    revokedAt: z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>;
  },
  z.core.$strip
>;
/**
 * Activity update payload.
 */
export declare const RecordUserSessionActivitySchema: z.ZodObject<
  {
    userAgent: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ipAddress: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    geoIp: z.ZodOptional<
      z.ZodNullable<
        z.ZodObject<
          {
            country: z.ZodOptional<
              z.ZodEnum<{
                readonly Afghanistan: 'AF';
                readonly AlandIslands: 'AX';
                readonly Albania: 'AL';
                readonly Algeria: 'DZ';
                readonly AmericanSamoa: 'AS';
                readonly Andorra: 'AD';
                readonly Angola: 'AO';
                readonly Anguilla: 'AI';
                readonly Antarctica: 'AQ';
                readonly AntiguaAndBarbuda: 'AG';
                readonly Argentina: 'AR';
                readonly Armenia: 'AM';
                readonly Aruba: 'AW';
                readonly Australia: 'AU';
                readonly Austria: 'AT';
                readonly Azerbaijan: 'AZ';
                readonly Bahamas: 'BS';
                readonly Bahrain: 'BH';
                readonly Bangladesh: 'BD';
                readonly Barbados: 'BB';
                readonly Belarus: 'BY';
                readonly Belgium: 'BE';
                readonly Belize: 'BZ';
                readonly Benin: 'BJ';
                readonly Bermuda: 'BM';
                readonly Bhutan: 'BT';
                readonly Bolivia: 'BO';
                readonly BonaireSintEustatiusAndSaba: 'BQ';
                readonly BosniaAndHerzegovina: 'BA';
                readonly Botswana: 'BW';
                readonly BouvetIsland: 'BV';
                readonly Brazil: 'BR';
                readonly BritishIndianOceanTerritory: 'IO';
                readonly BruneiDarussalam: 'BN';
                readonly Bulgaria: 'BG';
                readonly BurkinaFaso: 'BF';
                readonly Burundi: 'BI';
                readonly CaboVerde: 'CV';
                readonly Cambodia: 'KH';
                readonly Cameroon: 'CM';
                readonly Canada: 'CA';
                readonly CaymanIslands: 'KY';
                readonly CentralAfricanRepublic: 'CF';
                readonly Chad: 'TD';
                readonly Chile: 'CL';
                readonly China: 'CN';
                readonly ChristmasIsland: 'CX';
                readonly CocosKeelingIslands: 'CC';
                readonly Colombia: 'CO';
                readonly Comoros: 'KM';
                readonly Congo: 'CG';
                readonly CongoDemocraticRepublicOfThe: 'CD';
                readonly CookIslands: 'CK';
                readonly CostaRica: 'CR';
                readonly CoteDIvoire: 'CI';
                readonly Croatia: 'HR';
                readonly Cuba: 'CU';
                readonly Curacao: 'CW';
                readonly Cyprus: 'CY';
                readonly Czechia: 'CZ';
                readonly Denmark: 'DK';
                readonly Djibouti: 'DJ';
                readonly Dominica: 'DM';
                readonly DominicanRepublic: 'DO';
                readonly Ecuador: 'EC';
                readonly Egypt: 'EG';
                readonly ElSalvador: 'SV';
                readonly EquatorialGuinea: 'GQ';
                readonly Eritrea: 'ER';
                readonly Estonia: 'EE';
                readonly Eswatini: 'SZ';
                readonly Ethiopia: 'ET';
                readonly FalklandIslands: 'FK';
                readonly FaroeIslands: 'FO';
                readonly Fiji: 'FJ';
                readonly Finland: 'FI';
                readonly France: 'FR';
                readonly FrenchGuiana: 'GF';
                readonly FrenchPolynesia: 'PF';
                readonly FrenchSouthernTerritories: 'TF';
                readonly Gabon: 'GA';
                readonly Gambia: 'GM';
                readonly Georgia: 'GE';
                readonly Germany: 'DE';
                readonly Ghana: 'GH';
                readonly Gibraltar: 'GI';
                readonly Greece: 'GR';
                readonly Greenland: 'GL';
                readonly Grenada: 'GD';
                readonly Guadeloupe: 'GP';
                readonly Guam: 'GU';
                readonly Guatemala: 'GT';
                readonly Guernsey: 'GG';
                readonly Guinea: 'GN';
                readonly GuineaBissau: 'GW';
                readonly Guyana: 'GY';
                readonly Haiti: 'HT';
                readonly HeardIslandAndMcDonaldIslands: 'HM';
                readonly HolySee: 'VA';
                readonly Honduras: 'HN';
                readonly HongKong: 'HK';
                readonly Hungary: 'HU';
                readonly Iceland: 'IS';
                readonly India: 'IN';
                readonly Indonesia: 'ID';
                readonly Iran: 'IR';
                readonly Iraq: 'IQ';
                readonly Ireland: 'IE';
                readonly IsleOfMan: 'IM';
                readonly Israel: 'IL';
                readonly Italy: 'IT';
                readonly Jamaica: 'JM';
                readonly Japan: 'JP';
                readonly Jersey: 'JE';
                readonly Jordan: 'JO';
                readonly Kazakhstan: 'KZ';
                readonly Kenya: 'KE';
                readonly Kiribati: 'KI';
                readonly KoreaDemocraticPeoplesRepublicOf: 'KP';
                readonly KoreaRepublicOf: 'KR';
                readonly Kuwait: 'KW';
                readonly Kyrgyzstan: 'KG';
                readonly LaoPeoplesDemocraticRepublic: 'LA';
                readonly Latvia: 'LV';
                readonly Lebanon: 'LB';
                readonly Lesotho: 'LS';
                readonly Liberia: 'LR';
                readonly Libya: 'LY';
                readonly Liechtenstein: 'LI';
                readonly Lithuania: 'LT';
                readonly Luxembourg: 'LU';
                readonly Macao: 'MO';
                readonly Madagascar: 'MG';
                readonly Malawi: 'MW';
                readonly Malaysia: 'MY';
                readonly Maldives: 'MV';
                readonly Mali: 'ML';
                readonly Malta: 'MT';
                readonly MarshallIslands: 'MH';
                readonly Martinique: 'MQ';
                readonly Mauritania: 'MR';
                readonly Mauritius: 'MU';
                readonly Mayotte: 'YT';
                readonly Mexico: 'MX';
                readonly Micronesia: 'FM';
                readonly Moldova: 'MD';
                readonly Monaco: 'MC';
                readonly Mongolia: 'MN';
                readonly Montenegro: 'ME';
                readonly Montserrat: 'MS';
                readonly Morocco: 'MA';
                readonly Mozambique: 'MZ';
                readonly Myanmar: 'MM';
                readonly Namibia: 'NA';
                readonly Nauru: 'NR';
                readonly Nepal: 'NP';
                readonly Netherlands: 'NL';
                readonly NewCaledonia: 'NC';
                readonly NewZealand: 'NZ';
                readonly Nicaragua: 'NI';
                readonly Niger: 'NE';
                readonly Nigeria: 'NG';
                readonly Niue: 'NU';
                readonly NorfolkIsland: 'NF';
                readonly NorthMacedonia: 'MK';
                readonly NorthernMarianaIslands: 'MP';
                readonly Norway: 'NO';
                readonly Oman: 'OM';
                readonly Pakistan: 'PK';
                readonly Palau: 'PW';
                readonly Palestine: 'PS';
                readonly Panama: 'PA';
                readonly PapuaNewGuinea: 'PG';
                readonly Paraguay: 'PY';
                readonly Peru: 'PE';
                readonly Philippines: 'PH';
                readonly Pitcairn: 'PN';
                readonly Poland: 'PL';
                readonly Portugal: 'PT';
                readonly PuertoRico: 'PR';
                readonly Qatar: 'QA';
                readonly Reunion: 'RE';
                readonly Romania: 'RO';
                readonly RussianFederation: 'RU';
                readonly Rwanda: 'RW';
                readonly SaintBarthelemy: 'BL';
                readonly SaintHelenaAscensionAndTristanDaCunha: 'SH';
                readonly SaintKittsAndNevis: 'KN';
                readonly SaintLucia: 'LC';
                readonly SaintMartin: 'MF';
                readonly SaintPierreAndMiquelon: 'PM';
                readonly SaintVincentAndTheGrenadines: 'VC';
                readonly Samoa: 'WS';
                readonly SanMarino: 'SM';
                readonly SaoTomeAndPrincipe: 'ST';
                readonly SaudiArabia: 'SA';
                readonly Senegal: 'SN';
                readonly Serbia: 'RS';
                readonly Seychelles: 'SC';
                readonly SierraLeone: 'SL';
                readonly Singapore: 'SG';
                readonly SintMaarten: 'SX';
                readonly Slovakia: 'SK';
                readonly Slovenia: 'SI';
                readonly SolomonIslands: 'SB';
                readonly Somalia: 'SO';
                readonly SouthAfrica: 'ZA';
                readonly SouthGeorgiaAndTheSouthSandwichIslands: 'GS';
                readonly SouthSudan: 'SS';
                readonly Spain: 'ES';
                readonly SriLanka: 'LK';
                readonly Sudan: 'SD';
                readonly Suriname: 'SR';
                readonly SvalbardAndJanMayen: 'SJ';
                readonly Sweden: 'SE';
                readonly Switzerland: 'CH';
                readonly SyrianArabRepublic: 'SY';
                readonly Taiwan: 'TW';
                readonly Tajikistan: 'TJ';
                readonly Tanzania: 'TZ';
                readonly Thailand: 'TH';
                readonly TimorLeste: 'TL';
                readonly Togo: 'TG';
                readonly Tokelau: 'TK';
                readonly Tonga: 'TO';
                readonly TrinidadAndTobago: 'TT';
                readonly Tunisia: 'TN';
                readonly Turkiye: 'TR';
                readonly Turkmenistan: 'TM';
                readonly TurksAndCaicosIslands: 'TC';
                readonly Tuvalu: 'TV';
                readonly Uganda: 'UG';
                readonly Ukraine: 'UA';
                readonly UnitedArabEmirates: 'AE';
                readonly UnitedKingdom: 'GB';
                readonly UnitedStates: 'US';
                readonly UnitedStatesMinorOutlyingIslands: 'UM';
                readonly Uruguay: 'UY';
                readonly Uzbekistan: 'UZ';
                readonly Vanuatu: 'VU';
                readonly Venezuela: 'VE';
                readonly VietNam: 'VN';
                readonly VirginIslandsBritish: 'VG';
                readonly VirginIslandsUS: 'VI';
                readonly WallisAndFutuna: 'WF';
                readonly WesternSahara: 'EH';
                readonly Yemen: 'YE';
                readonly Zambia: 'ZM';
                readonly Zimbabwe: 'ZW';
              }>
            >;
            region: z.ZodOptional<z.ZodString>;
            city: z.ZodOptional<z.ZodString>;
            timezone: z.ZodOptional<z.ZodString>;
            latitude: z.ZodOptional<z.ZodNumber>;
            longitude: z.ZodOptional<z.ZodNumber>;
          },
          z.core.$strip
        >
      >
    >;
  },
  z.core.$strip
>;
/**
 * Session data safe to return to the owning user or an authorized admin.
 *
 * Does not expose `tokenHash` or precise GeoIP coordinates.
 */
export declare const UserSessionContractSchema: z.ZodObject<
  {
    id: z.ZodUUID;
    userId: z.ZodUUID;
    deviceName: z.ZodNullable<z.ZodString>;
    userAgent: z.ZodNullable<z.ZodString>;
    ipAddress: z.ZodNullable<z.ZodString>;
    geoIp: z.ZodNullable<
      z.ZodObject<
        {
          timezone: z.ZodOptional<z.ZodString>;
          country: z.ZodOptional<
            z.ZodEnum<{
              readonly Afghanistan: 'AF';
              readonly AlandIslands: 'AX';
              readonly Albania: 'AL';
              readonly Algeria: 'DZ';
              readonly AmericanSamoa: 'AS';
              readonly Andorra: 'AD';
              readonly Angola: 'AO';
              readonly Anguilla: 'AI';
              readonly Antarctica: 'AQ';
              readonly AntiguaAndBarbuda: 'AG';
              readonly Argentina: 'AR';
              readonly Armenia: 'AM';
              readonly Aruba: 'AW';
              readonly Australia: 'AU';
              readonly Austria: 'AT';
              readonly Azerbaijan: 'AZ';
              readonly Bahamas: 'BS';
              readonly Bahrain: 'BH';
              readonly Bangladesh: 'BD';
              readonly Barbados: 'BB';
              readonly Belarus: 'BY';
              readonly Belgium: 'BE';
              readonly Belize: 'BZ';
              readonly Benin: 'BJ';
              readonly Bermuda: 'BM';
              readonly Bhutan: 'BT';
              readonly Bolivia: 'BO';
              readonly BonaireSintEustatiusAndSaba: 'BQ';
              readonly BosniaAndHerzegovina: 'BA';
              readonly Botswana: 'BW';
              readonly BouvetIsland: 'BV';
              readonly Brazil: 'BR';
              readonly BritishIndianOceanTerritory: 'IO';
              readonly BruneiDarussalam: 'BN';
              readonly Bulgaria: 'BG';
              readonly BurkinaFaso: 'BF';
              readonly Burundi: 'BI';
              readonly CaboVerde: 'CV';
              readonly Cambodia: 'KH';
              readonly Cameroon: 'CM';
              readonly Canada: 'CA';
              readonly CaymanIslands: 'KY';
              readonly CentralAfricanRepublic: 'CF';
              readonly Chad: 'TD';
              readonly Chile: 'CL';
              readonly China: 'CN';
              readonly ChristmasIsland: 'CX';
              readonly CocosKeelingIslands: 'CC';
              readonly Colombia: 'CO';
              readonly Comoros: 'KM';
              readonly Congo: 'CG';
              readonly CongoDemocraticRepublicOfThe: 'CD';
              readonly CookIslands: 'CK';
              readonly CostaRica: 'CR';
              readonly CoteDIvoire: 'CI';
              readonly Croatia: 'HR';
              readonly Cuba: 'CU';
              readonly Curacao: 'CW';
              readonly Cyprus: 'CY';
              readonly Czechia: 'CZ';
              readonly Denmark: 'DK';
              readonly Djibouti: 'DJ';
              readonly Dominica: 'DM';
              readonly DominicanRepublic: 'DO';
              readonly Ecuador: 'EC';
              readonly Egypt: 'EG';
              readonly ElSalvador: 'SV';
              readonly EquatorialGuinea: 'GQ';
              readonly Eritrea: 'ER';
              readonly Estonia: 'EE';
              readonly Eswatini: 'SZ';
              readonly Ethiopia: 'ET';
              readonly FalklandIslands: 'FK';
              readonly FaroeIslands: 'FO';
              readonly Fiji: 'FJ';
              readonly Finland: 'FI';
              readonly France: 'FR';
              readonly FrenchGuiana: 'GF';
              readonly FrenchPolynesia: 'PF';
              readonly FrenchSouthernTerritories: 'TF';
              readonly Gabon: 'GA';
              readonly Gambia: 'GM';
              readonly Georgia: 'GE';
              readonly Germany: 'DE';
              readonly Ghana: 'GH';
              readonly Gibraltar: 'GI';
              readonly Greece: 'GR';
              readonly Greenland: 'GL';
              readonly Grenada: 'GD';
              readonly Guadeloupe: 'GP';
              readonly Guam: 'GU';
              readonly Guatemala: 'GT';
              readonly Guernsey: 'GG';
              readonly Guinea: 'GN';
              readonly GuineaBissau: 'GW';
              readonly Guyana: 'GY';
              readonly Haiti: 'HT';
              readonly HeardIslandAndMcDonaldIslands: 'HM';
              readonly HolySee: 'VA';
              readonly Honduras: 'HN';
              readonly HongKong: 'HK';
              readonly Hungary: 'HU';
              readonly Iceland: 'IS';
              readonly India: 'IN';
              readonly Indonesia: 'ID';
              readonly Iran: 'IR';
              readonly Iraq: 'IQ';
              readonly Ireland: 'IE';
              readonly IsleOfMan: 'IM';
              readonly Israel: 'IL';
              readonly Italy: 'IT';
              readonly Jamaica: 'JM';
              readonly Japan: 'JP';
              readonly Jersey: 'JE';
              readonly Jordan: 'JO';
              readonly Kazakhstan: 'KZ';
              readonly Kenya: 'KE';
              readonly Kiribati: 'KI';
              readonly KoreaDemocraticPeoplesRepublicOf: 'KP';
              readonly KoreaRepublicOf: 'KR';
              readonly Kuwait: 'KW';
              readonly Kyrgyzstan: 'KG';
              readonly LaoPeoplesDemocraticRepublic: 'LA';
              readonly Latvia: 'LV';
              readonly Lebanon: 'LB';
              readonly Lesotho: 'LS';
              readonly Liberia: 'LR';
              readonly Libya: 'LY';
              readonly Liechtenstein: 'LI';
              readonly Lithuania: 'LT';
              readonly Luxembourg: 'LU';
              readonly Macao: 'MO';
              readonly Madagascar: 'MG';
              readonly Malawi: 'MW';
              readonly Malaysia: 'MY';
              readonly Maldives: 'MV';
              readonly Mali: 'ML';
              readonly Malta: 'MT';
              readonly MarshallIslands: 'MH';
              readonly Martinique: 'MQ';
              readonly Mauritania: 'MR';
              readonly Mauritius: 'MU';
              readonly Mayotte: 'YT';
              readonly Mexico: 'MX';
              readonly Micronesia: 'FM';
              readonly Moldova: 'MD';
              readonly Monaco: 'MC';
              readonly Mongolia: 'MN';
              readonly Montenegro: 'ME';
              readonly Montserrat: 'MS';
              readonly Morocco: 'MA';
              readonly Mozambique: 'MZ';
              readonly Myanmar: 'MM';
              readonly Namibia: 'NA';
              readonly Nauru: 'NR';
              readonly Nepal: 'NP';
              readonly Netherlands: 'NL';
              readonly NewCaledonia: 'NC';
              readonly NewZealand: 'NZ';
              readonly Nicaragua: 'NI';
              readonly Niger: 'NE';
              readonly Nigeria: 'NG';
              readonly Niue: 'NU';
              readonly NorfolkIsland: 'NF';
              readonly NorthMacedonia: 'MK';
              readonly NorthernMarianaIslands: 'MP';
              readonly Norway: 'NO';
              readonly Oman: 'OM';
              readonly Pakistan: 'PK';
              readonly Palau: 'PW';
              readonly Palestine: 'PS';
              readonly Panama: 'PA';
              readonly PapuaNewGuinea: 'PG';
              readonly Paraguay: 'PY';
              readonly Peru: 'PE';
              readonly Philippines: 'PH';
              readonly Pitcairn: 'PN';
              readonly Poland: 'PL';
              readonly Portugal: 'PT';
              readonly PuertoRico: 'PR';
              readonly Qatar: 'QA';
              readonly Reunion: 'RE';
              readonly Romania: 'RO';
              readonly RussianFederation: 'RU';
              readonly Rwanda: 'RW';
              readonly SaintBarthelemy: 'BL';
              readonly SaintHelenaAscensionAndTristanDaCunha: 'SH';
              readonly SaintKittsAndNevis: 'KN';
              readonly SaintLucia: 'LC';
              readonly SaintMartin: 'MF';
              readonly SaintPierreAndMiquelon: 'PM';
              readonly SaintVincentAndTheGrenadines: 'VC';
              readonly Samoa: 'WS';
              readonly SanMarino: 'SM';
              readonly SaoTomeAndPrincipe: 'ST';
              readonly SaudiArabia: 'SA';
              readonly Senegal: 'SN';
              readonly Serbia: 'RS';
              readonly Seychelles: 'SC';
              readonly SierraLeone: 'SL';
              readonly Singapore: 'SG';
              readonly SintMaarten: 'SX';
              readonly Slovakia: 'SK';
              readonly Slovenia: 'SI';
              readonly SolomonIslands: 'SB';
              readonly Somalia: 'SO';
              readonly SouthAfrica: 'ZA';
              readonly SouthGeorgiaAndTheSouthSandwichIslands: 'GS';
              readonly SouthSudan: 'SS';
              readonly Spain: 'ES';
              readonly SriLanka: 'LK';
              readonly Sudan: 'SD';
              readonly Suriname: 'SR';
              readonly SvalbardAndJanMayen: 'SJ';
              readonly Sweden: 'SE';
              readonly Switzerland: 'CH';
              readonly SyrianArabRepublic: 'SY';
              readonly Taiwan: 'TW';
              readonly Tajikistan: 'TJ';
              readonly Tanzania: 'TZ';
              readonly Thailand: 'TH';
              readonly TimorLeste: 'TL';
              readonly Togo: 'TG';
              readonly Tokelau: 'TK';
              readonly Tonga: 'TO';
              readonly TrinidadAndTobago: 'TT';
              readonly Tunisia: 'TN';
              readonly Turkiye: 'TR';
              readonly Turkmenistan: 'TM';
              readonly TurksAndCaicosIslands: 'TC';
              readonly Tuvalu: 'TV';
              readonly Uganda: 'UG';
              readonly Ukraine: 'UA';
              readonly UnitedArabEmirates: 'AE';
              readonly UnitedKingdom: 'GB';
              readonly UnitedStates: 'US';
              readonly UnitedStatesMinorOutlyingIslands: 'UM';
              readonly Uruguay: 'UY';
              readonly Uzbekistan: 'UZ';
              readonly Vanuatu: 'VU';
              readonly Venezuela: 'VE';
              readonly VietNam: 'VN';
              readonly VirginIslandsBritish: 'VG';
              readonly VirginIslandsUS: 'VI';
              readonly WallisAndFutuna: 'WF';
              readonly WesternSahara: 'EH';
              readonly Yemen: 'YE';
              readonly Zambia: 'ZM';
              readonly Zimbabwe: 'ZW';
            }>
          >;
          region: z.ZodOptional<z.ZodString>;
          city: z.ZodOptional<z.ZodString>;
        },
        z.core.$strip
      >
    >;
    lastSeenAt: z.ZodNullable<z.ZodISODateTime>;
    expiresAt: z.ZodISODateTime;
    revokedAt: z.ZodNullable<z.ZodISODateTime>;
    createdAt: z.ZodISODateTime;
    updatedAt: z.ZodISODateTime;
  },
  z.core.$strip
>;
export type UserSessionGeoIpInput = z.infer<typeof UserSessionGeoIpSchema>;
export type PublicUserSessionGeoIpInput = z.infer<
  typeof PublicUserSessionGeoIpSchema
>;
export type UserSessionEntitySchemaType = z.infer<
  typeof UserSessionEntitySchema
>;
export type CreateUserSessionEntityInput = z.infer<
  typeof CreateUserSessionEntitySchema
>;
export type UpdateUserSessionEntityInput = z.infer<
  typeof UpdateUserSessionEntitySchema
>;
export type RecordUserSessionActivityInput = z.infer<
  typeof RecordUserSessionActivitySchema
>;
export type UserSessionContractSchemaType = z.infer<
  typeof UserSessionContractSchema
>;
