apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: aerealith-platform
    app.kubernetes.io/managed-by: flux

spec:
  interval: 30m

  releaseName: kube-prometheus-stack
  targetNamespace: observability
  storageNamespace: observability

  chart:
    spec:
      chart: kube-prometheus-stack
      version: '88.5.4'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h

  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
      valuesKey: values.yaml

  install:
    createNamespace: false
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback

  rollback:
    cleanupOnFail: true
    timeout: 15m

  timeout: 15m
