apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-serving-cert-approver
  namespace: kubelet-serving-cert-approver
  labels:
    app.kubernetes.io/name: kubelet-serving-cert-approver
    app.kubernetes.io/instance: kubelet-serving-cert-approver
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: aerealith-platform
    app.kubernetes.io/managed-by: flux
automountServiceAccountToken: true
