apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: aerealith-flux-controllers
  namespace: observability
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: flux
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: aerealith-platform
    app.kubernetes.io/managed-by: flux
spec:
  namespaceSelector:
    matchNames:
      - flux-system

  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - kustomize-controller
          - notification-controller
          - source-controller

  podTargetLabels:
    - app

  podMetricsEndpoints:
    - port: http-prom
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
